### ISSUE TITLE
TGN

### ISSUE THREAD

**Issue by tchaton** [benedekrozemberczki/pytorch_geometric_temporal#1]
https://arxiv.org/abs/2006.10637

**Comment by benedekrozemberczki** [comment]
Hi there Thomas!

This paper is already on my backlog ( approx. 50 papers by now :D :D :') ). The package is going to be part of an ML system design paper which I plan to submit in November-December. If you want to join in the development I am happy to add you to the project and the paper as a co-author.

Regards,

Benedek

**Comment by tchaton** [comment]
Hey @benedekrozemberczki,

Sounds interesting ! I will see if I can help you out.

I already have my hand pretty packed with https://github.com/nicolas-chaulet/torch-points3d for which I am of the main author.

I have sent you an invitation to join our Slack related to project around Pytorch Geometric.

Best regards,
Thomas Chaton.
