### ISSUE TITLE
edge data in st gcn

### ISSUE THREAD

**Issue by always-ready2learn** [benedekrozemberczki/pytorch_geometric_temporal#101]
Hi, 

The stgcn model seems to take targets against node features only, Is it possible to pass in node and edge features but define targets against edges i.e. edge_weights for link prediction / classification?

TIA

**Comment by benedekrozemberczki** [comment]
Yes, there is no reason not to - did you try this?

**Comment by always-ready2learn** [comment]
Apologies, I should have mentioned data iterator instead of stgcn to be more precise. I am using staticgraphtemporalsignal iterator for my graph. I’ll then iterate and train on st-gcn to get edge prediction. I sort of know how to do edge prediction on stgcn. Im stuck at defining data. I want to pass node features, edge features, edge index, targets against edge features in staticgraphtemporalsignal. Acc to the manual it takes in targets against node features. Apologies again for the limited knowledge, this is my first experiment in stgcn. Previously, I did some experiments in pyG for node and edge classification. 

Thanks for your response.

**Comment by always-ready2learn** [comment]
This is what I get : 
assert len(self.features) == len(
            self.targets), "Temporal dimension inconsistency."

**Comment by benedekrozemberczki** [comment]
Okay, let me create this week a modification of the iterator classes which
allows you to do this - alternatively you can concatenate your edge
features and the edge target and by an indexing trick get separate them
when these are on GPU - might be tricky with respect to typing.

**Comment by always-ready2learn** [comment]
Thank you..
