### ISSUE TITLE
Attention GCN example

### ISSUE THREAD

**Issue by soumbane** [benedekrozemberczki/pytorch_geometric_temporal#102]
Hi, 

I am trying to work with the attention based STGCN by using STConv. However, I am get some shape matching errors. Could you provide an example of the attention based stgcn similar to how you provided examples for recurrent based DCRNN.

Also how to use the batched static signal iterator to generate batches of static graph temporal signal to be used by stgcn?

Thank you for your help.

**Comment by benedekrozemberczki** [comment]
Look at the examples folder.

**Comment by soumbane** [comment]
Yes, I looked at the examples folder but there are only examples of recurrent models such as DCRNN. I am new to this topic, so I was looking for temporal graph attention layers such as examples of STConv layer. Would it be possible to add an example of STConv on the example dataset (Chicken Pox dataset)?
