### ISSUE TITLE
python setup.py test error

### ISSUE THREAD

**Issue by DongDChen** [benedekrozemberczki/pytorch_geometric_temporal#103]
Hi 

when I perform the command "python setup.py test", It comes to the error: 
ERROR test/attention_test.py - OSError: [WinError 127] Cannot find the specified program，
ERROR test/batch_test.py - OSError: [WinError 127] Cannot find the specified program，
ERROR test/dataset_test.py - OSError: [WinError 127] Cannot find the specified program，
ERROR test/recurrent_test.py - OSError: [WinError 127] Cannot find the specified program，

![1632806651(1)](https://user-images.githubusercontent.com/20920484/135028169-cd649402-8d15-4219-b3c9-112bb224be49.jpg)

My environment is win10+anaconda1.7.2+python 3.8.10+pytorch1.8.0 
![1632806816(1)](https://user-images.githubusercontent.com/20920484/135028347-6ad1cb52-d441-4436-a659-59c4854a3d69.jpg)

I have tried the solution searched on the internet "replace the libssl-1_1-x64.dll in D:\Anaconda3\envs\pytorch\Library\bin with that in DLLs" but still failed.

Thank you

**Comment by haijunkenan** [comment]
I fixed this when dealing with another problem...
