### ISSUE TITLE
Using vectors for each time step in TGCN?

### ISSUE THREAD

**Issue by naman-ali** [benedekrozemberczki/pytorch_geometric_temporal#109]
In TGCN, how can I use a vector containing multiple values (instead of just a value) for each time step as node features?

If you can recommend any other work that supports this, that would be great too.

**Comment by benedekrozemberczki** [comment]
What do you mean?

**Comment by naman-ali** [comment]
In TGCN, a node feature is vector with the length of time steps. For each time step, there is only one value (speed) specified, which will be predicted at the end for t+1. 

I am dealing with a problem that I need to predict multiple values (not just speed) for each time step. 

For example, assume at time t+1 I want to predict each individual cars speeds that are in the road (not only one speed for all the cars).

**Comment by benedekrozemberczki** [comment]
Dear Ali,

You can pass in a matrix as a target.

Could you start the repo and hit follow?

Bests,
Benedek

**Comment by naman-ali** [comment]
Thank you Benedek.

What do you mean by starting the repo? and follow?

**Comment by alexriedel1** [comment]
![image](https://user-images.githubusercontent.com/54716527/140023252-24f4ba42-f092-4ce1-be23-7f2676757817.png)
👍

**Comment by naman-ali** [comment]
Thank you Alex, so Benedek meant star, not start. Got it.
