### ISSUE TITLE
What does the 'X' in the pedalme dataset json file mean?

### ISSUE THREAD

**Issue by SANGDONKIM** [benedekrozemberczki/pytorch_geometric_temporal#110]
Hi, 

What does the 'X' in the pedalme dataset json file mean?

I thought of it as a target.

But are the 'demand' of the original csv file and the 'X' of the json file different?

CSV data link : https://github.com/benedekrozemberczki/spatiotemporal_datasets

**Comment by benedekrozemberczki** [comment]
These are normalized as the paper states.
