### ISSUE TITLE
out of bounds for dimension error 

### ISSUE THREAD

**Issue by SANGDONKIM** [benedekrozemberczki/pytorch_geometric_temporal#111]
Hi, 

I'm trying to use the gclstm model.

The following error occurs.

I adjusted the value of filter because a dimension error occurred.

However, another error occurs.
![image](https://user-images.githubusercontent.com/49220904/140797164-20c3b2fc-8fb6-4d61-aedf-e001f2dd987d.png)
![image](https://user-images.githubusercontent.com/49220904/140797197-adac0a58-c070-4578-8656-2e056c3f5cc3.png)

![image](https://user-images.githubusercontent.com/49220904/140795513-6248bdea-7972-4ec8-9fdf-915cd2503010.png)

Can you tell me the cause of the error and the solution?

**The DCRNN layer works normally.**

The shape of my data is:

![image](https://user-images.githubusercontent.com/49220904/140796350-d5e205d3-248d-44ba-a55c-758af1c50a69.png)

**Comment by benedekrozemberczki** [comment]
Can you provide more details?

**Comment by SANGDONKIM** [comment]
I provided additional information.

Need more information?


It's difficult because I don't understand the cause of the error...

**Comment by alexriedel1** [comment]
@SANGDONKIM  can you give a minimal working example to reproduce the error?

**Comment by SANGDONKIM** [comment]
I checked the pedalme dataset's source file and tried to make the dataset identical.

This was the wrong approach, and when I reconstructed the dataset in the form of a chicken box dataset, it returns without error.

@alexriedel1 

Although the data set format is the same as the example reproduced by alexriedel1, the cause of the error has not yet been found.


Thanks so much for replying

**Comment by ThisisHubert** [comment]
I have a question about this as I'm implementing a model using GCLSTM, 
correct me if my understanding is wrong, shouldn't it be DynamicGraphStaticSignal for GCLSTM as the paper mentioned that only the edge on the graph is changing?
