### ISSUE TITLE
How to perform MultiVariate Time series Anomaly Detection

### ISSUE THREAD

**Issue by m-ali-awan** [benedekrozemberczki/pytorch_geometric_temporal#114]
I am working on MultiVariate Time series Anomaly Detection, and the data from the normal regime should be considered only. I can find many papers on it, but cannot find any useful resources in form of blogs or codes.

So, is there any such implementation available in pytorch_geometric_temporal, or anywhere else?

If anyone can share it here, I would be grateful for that.

Thanks, 
Regards, 
Muhammad Ali

**Comment by benedekrozemberczki** [comment]
Hi @m-ali-awan I do not know. You might have to go with something that you build from scratch! Could you star the repo?

**Comment by m-ali-awan** [comment]
Thanks @benedekrozemberczki , but there can be any data blocks or something from where I can start?
Kindly do post it here, if you find any.
Thanks
