### ISSUE TITLE
How to add node features? 

### ISSUE THREAD

**Issue by SANGDONKIM** [benedekrozemberczki/pytorch_geometric_temporal#115]
Hi, 

I am analyzing using the dcrnn model implemented in pytorch geometric temporal.

I want to add another variable to the node feature, but I don't understand exactly how. 

Can you give me some hint or code?

**Comment by benedekrozemberczki** [comment]
Hi there,

Could you describe your problem with code and linear algebra.

Thanks.

Benedek
