### ISSUE TITLE
Shape of `y_hat` and `snapshot.y` in examples

### ISSUE THREAD

**Issue by bkj** [benedekrozemberczki/pytorch_geometric_temporal#116]
In the examples, `y_hat` has shape `(bs, 1)` while `snapshot.y` has shape `(bs,)`:
  https://github.com/benedekrozemberczki/pytorch_geometric_temporal/blob/master/examples/recurrent/tgcn_example.py#L38

In the current implementation (in torch=1.9.0) `y_hat - snapshot.y` has shape `(bs, bs)`, which seems incorrect.  I think it should be: `y_hat.squeeze() - snapshot.y` instead.

**Comment by benedekrozemberczki** [comment]
Hi there @bkj,

Do you want to PR this?

Benedek
