### ISSUE TITLE
Performance vs. simple baselines

### ISSUE THREAD

**Issue by bkj** [benedekrozemberczki/pytorch_geometric_temporal#117]
Hello --

I ran the [DCRNN example](https://github.com/benedekrozemberczki/pytorch_geometric_temporal/blob/master/examples/recurrent/dcrnn_example.py) (plus the fix I describe in this issue: https://github.com/benedekrozemberczki/pytorch_geometric_temporal/issues/116), and get
```
MSE: 0.7408
```

However, if I do a simple linear regression on `dataset.features`, I seem to get a better MSE:
```
import numpy as np
from sklearn.linear_model import LinearRegression

X_train = np.row_stack(train_dataset.features)
y_train = np.hstack(train_dataset.targets)

X_test = np.row_stack(test_dataset.features)
y_test = np.hstack(test_dataset.targets)

model = LinearRegression().fit(X_train, y_train)
pred  = model.predict(X_test)
print("MSE: ", ((y_test - pred) ** 2).mean())
# MSE:  0.7044159007776996
```

Couple of questions:
 - Is there a bug in my code above?  I'm new to the package, so perhaps I'm misinterpreting the data structures.
 - I understand this is a small example dataset -- but do you have examples of models / datasets where these methods outperform baseline models?  I'll play w/ the other datasets included in this package, but figured I'd open this issue in the meantime.

Thanks!
~ Ben

**Comment by benedekrozemberczki** [comment]
Yes, one of the main take aways from the system design paper that these recurrent papers and others alike have an extremely poor performance. We played with ARIMA and recurrent GCN models struggle.

**Comment by bkj** [comment]
Ah OK -- thanks for the response.!

To clarify -- I'm not really specifically interested in DCRNN or really the ChickenPox dataset -- I'm just curious to see a model / dataset combination where `pytorch_geometric_temporal` does well compared to a simple baseline.  Any ideas on that?  

Or does your previous comment mean that these `pytorch_geometric_temporal` generally don't outperform simple baselines (yet :wink:)?

Thanks!

**Comment by benedekrozemberczki** [comment]
GMAN an the attention based models work well on everything. The recurrent
ones work poorly on problems with heterophily.
