### ISSUE TITLE
Can I use mini-batch in DCRNN?

### ISSUE THREAD

**Issue by 3riccc** [benedekrozemberczki/pytorch_geometric_temporal#12]
In the example given in the documentation, you use DCRNN to process some data which has the format like [node_num, node_feature_dim]. I understand that, but the problem I want to solve now is a little bit complicated.

I want to train a batch of graphs, which has same edge indexs but different node features. Imaging a bunch of nodes interact in a graph through a fixed topology and the feature of these node will change because of the interaction. Through sampling by time, I can get many graphs which have same topology and different node featuers.

Now I want to compute the node features in the next timestep using there current features and the topology.  The question is 'how to map the node feature of many graphs(which has same topology) in one forward propagation.' I think this might be solved by mini-batch, but I cant find things about that in the documention.

I have tried to make the data fromat like [batch, node_num, node_features] but it doesn't work, The error is like this:

RuntimeError: Tensors must have same number of dimensions: got 3 and 2

So, Is there any way to solve this? thank you!

**Comment by benedekrozemberczki** [comment]
Hi there @3riccc,

What do you mean by sampling by time? What is the exact use case? I would like to help, but the batching strategy highly depends on the use case and the sampling. Can you elaborate?

Bests,

Benedek

**Comment by 3riccc** [comment]
Thank you. Let me explain.

Imagine a spring system in which small balls are connected by springs, the balls are nodes and springs are edges. The ball moves under the action of elastic force. Thus the node features will be the position and velocity of the balls and the topology is fixed.

'Sampling' means take a snapshot of this system, Concretely, I'll record the node features(position and velocity of the balls) at timestep 0, timestep 1, timestep2 and so on... The task is to predict the node feature at time t+1 using the node feature at time t and the known topology. If I can make accurate prediction, that means I learned the dynamics of this system.

Here is why I want to use batch: if Ihave to many snapshots of the system, e.g from timestep0, timestep1 ... to timestep 10000. 
 which means we have a huge dataset of node features like [length, node_num, node_feature_dim] and a fixed topology. To run this dataset, I have to predict 10000 times iteratively. 

So can I use some batch method to run it in one forward propagation. Like the input is the first 100 step snapshots of the system and the output will be the 1 to 101 step?

**Comment by benedekrozemberczki** [comment]
Dear @3riccc,

1.You would need to update the hidden states in the RNN, so you cannot batch. You could accumulate the loss for the sequence of graphs with a discrete data iterator with a static graph.  Our framework allows for this, please look at the read the docs. 

2. However, You could have multiple sequences - you run the simulation multiple times. In this case, you could have a diagonal block matrix-based batching. This can result in better training and also you could have more stable gradients. 

3. If you are willing to open source the dataset we are happy to add you as a co-author for the library. 

4. Please do not forget to cite the paper if you use the library in the end.

Bests,

Benedek

**Comment by benedekrozemberczki** [comment]
Hi there @3ricc,

Did this solve your issues?

Bests,

Benedek

**Comment by 3ricc** [comment]
Hi there @benedekrozemberczki,

You mentioned the wrong person. The one you are looking for is @3riccc with 3 cs, not two.

Best regards,

Eric

**Comment by benedekrozemberczki** [comment]
Hi there @3riccc ,

Did this solve your issues?

Bests,

Benedek

**Comment by wangqh1996** [comment]
Hi there @3riccc ,
I found that my question and data are very similar to yours, "which has same edge indexs but different node features ", have you solved it? Could you please share your solution?
Bests wishes
