### ISSUE TITLE
EvolveGCNO

### ISSUE THREAD

**Issue by chlorophyllccc** [benedekrozemberczki/pytorch_geometric_temporal#126]
Hi, I would like to use the EvolveGCN for my own task, and I just went through the source code. I am a little confused.

I am wondering for EvolveGCNO here if the model keeps the weight for GCN constantly instead of updating it over time?

![image](https://user-images.githubusercontent.com/61045930/148734722-c2a0f26f-41de-4beb-9f0a-97dfd194ff37.png)

However, the model updates the weights of GCN by taking the output of the RNN according to the paper. Thanks in advance!

**Comment by SherylHYX** [comment]
Hello @chlorophyllccc , W is a copy of self.weight but only with different dimensions. Look at this example:
![image](https://user-images.githubusercontent.com/43345664/148736641-c7e8b2a3-757c-4d7a-a30b-00376142d504.png)

**Comment by chlorophyllccc** [comment]
Hi @SherylHYX, Thanks for the reply!

Yeah, I am aware that changing W will affect self.weight. My question is that for every time step the input for RNN is always initial_weight.data but shouldn't we use the output of RNN from the last step?

Or have I missed something? Thanks!

**Comment by SherylHYX** [comment]
The input is not always initial_weight.data because after the first epoch self.weight will no longer be None.

**Comment by chlorophyllccc** [comment]
Ohhhh! I got it. Thanks for the patience!

**Comment by SherylHYX** [comment]
Nice that you finally understand!
