### ISSUE TITLE
ImportError: cannot import name 'container_abcs' from 'torch._six' 

### ISSUE THREAD

**Issue by pflashgary** [benedekrozemberczki/pytorch_geometric_temporal#127]
Hi, running into this issue to install  PyTorch Geometric Temporal. This is what I did:

```python
import torch
from IPython.display import clear_output
pt_version = torch.__version__
print(pt_version)
1.10.0+cu111
```

Then

```sh
pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-${pt_version}.html
pip install torch-sparse -f https://pytorch-geometric.com/whl/torch-${pt_version}.html
pip install torch-cluster -f https://pytorch-geometric.com/whl/torch-${pt_version}.html
pip install torch-spline-conv -f https://pytorch-geometric.com/whl/torch-${pt_version}.html
pip install torch-geometric
pip install torch-geometric-temporal
```
After successfully installing all packages:

```python
from torch_geometric_temporal.dataset import METRLADatasetLoader
ImportError: cannot import name 'container_abcs' from 'torch._six' 
```

**Comment by pflashgary** [comment]
It looks to me `pip install torch-geometric-temporal` uninstalls the latest version of torch-geometric (`torch-geometric-2.0.3`) and installs `torch-geometric-1.7.0`, hence the ImportError. Is there a way to avoid that?

```bash
Attempting uninstall: torch-geometric
    Found existing installation: torch-geometric 2.0.3
    Uninstalling torch-geometric-2.0.3:
      Successfully uninstalled torch-geometric-2.0.3
Successfully installed torch-geometric-1.7.0 torch-geometric-temporal-0.42
```

**Comment by Chrixtar** [comment]
Hi, I ran into exactly the same issue today.
The PyTorch 1.9.0 setup of PyTorch Geometric Temporal is inconsistent, as PyTorch Geometric 1.7.0 is not compatible with PyTorch 1.9.0.
Also, I would like to know about the reasons for staying with version 1.7.0. Are there major changes preventing an upgrade to 2.0 ?

**Comment by benedekrozemberczki** [comment]
I do not think so, feel free to open a PR.

**Comment by pflashgary** [comment]
Hi Chrixtar and Benedek

Sorry I should be sending a PR instead of raising an issue. Though I'm not very experienced with installing and testing python packages locally. Am I correct to assume we only need to relax this dependency [here](https://github.com/benedekrozemberczki/pytorch_geometric_temporal/blob/67992e0cd26ca961f98e62ff0dae2b1858833e3e/setup.py#L10):

**from** 

```python
install_requires = [
    "decorator==4.4.2",
    "torch",
    "torch_sparse",
    "torch_scatter",
    "torch_cluster",
    "torch_spline_conv",
    "torch_geometric==1.7.0",
    "numpy",
    "scipy",
    "tqdm",
    "six",

```

**to** 

```python
install_requires = [
    "decorator==4.4.2",
    "torch",
    "torch_sparse",
    "torch_scatter",
    "torch_cluster",
    "torch_spline_conv",
    "torch_geometric>=1.7.1",
    "numpy",
    "scipy",
    "tqdm",
    "six",

```

**Comment by benedekrozemberczki** [comment]
We released a new version.
