### ISSUE TITLE
temporal_signal_split does not take into account additional attributes

### ISSUE THREAD

**Issue by tforgaard** [benedekrozemberczki/pytorch_geometric_temporal#128]
Hi,
Added additional attributes are removed after invoking the temporal_signal_split function as optional additional attributes are not passed to the initialisation method. Not sure if this is the pythonic way but it can easily be solved by adding the last line to all initialisations methods in train_test_split.py

```
        train_iterator = DynamicGraphTemporalSignal(
            data_iterator.edge_indices[0:train_snapshots],
            data_iterator.edge_weights[0:train_snapshots],
            data_iterator.features[0:train_snapshots],
            data_iterator.targets[0:train_snapshots],
            **{key: data_iterator.__getattribute__(key)[0:train_snapshots] for key in data_iterator.additional_feature_keys}
        )
```

**Comment by benedekrozemberczki** [comment]
Do you want to open a PR @tforgaard?
