### ISSUE TITLE
Are EvovleGCN example temporal?

### ISSUE THREAD

**Issue by gao462** [benedekrozemberczki/pytorch_geometric_temporal#13]
In the example of EvolveGCN, I only saw a weighted static graph with 1000 nodes of 100 dimension features, 7000 edges with edge weights, where is the temporal information?

**Comment by benedekrozemberczki** [comment]
You can take the read the docs example and use the EvolveGCN model with that.

**Comment by gao462** [comment]
I am somehow not sure about the usage based only on EvolveGCN document and example, is this works only on a single step of a sequence of snapshots just like RNNCell of PyTorch? And the example is how it works with a single step of grap snapshot inputs?

**Comment by benedekrozemberczki** [comment]
Yes it is a single cell.

**Comment by tonygracious** [comment]
How can I make the EvolveGCN temporal with embedding learning using multiple Snapshots?

**Comment by johnny12150** [comment]
I found [this example](https://pytorch-geometric-temporal.readthedocs.io/en/latest/notes/introduction.html#applications) helpful.
