### ISSUE TITLE
How to Use a GPU

### ISSUE THREAD

**Issue by lishiyuan0709** [benedekrozemberczki/pytorch_geometric_temporal#130]
Hello, what do I need to do if I want to use the GPU in Pytorch_geometric_temporal? My tests now show that it's all CPU use and I have CUDA10.2 and Pytorch- GPU 1.10.2 installed

**Comment by benedekrozemberczki** [comment]
Hi there @lishiyuan0709 Can you be more specific?

**Comment by lishiyuan0709** [comment]
It is that I ran the sample code in Pytorch_geometric_temporal, but I found that the program is running on CPU and it is running slow, I want to run it on GPU, but I can't how to run it. I already have Pytorch and Pytorch-geometric installed for CUDA 10.2.

**Comment by benedekrozemberczki** [comment]
You can transfer the model and the snapshots.

**Comment by lishiyuan0709** [comment]
I'll give it a try
