### ISSUE TITLE
Temporal, multigraph with temporal node features

### ISSUE THREAD

**Issue by MichaelHopwood** [benedekrozemberczki/pytorch_geometric_temporal#135]
I'm looking to conduct a temporal prediction task with all of the following simultaneous properties:
1) Single or Multiple edge features (data can be consolidated to one feature although multiple exist in domain)
2) The adjacencies are temporal
3) Exogeneous temporal node features (X data)
4) Endogenous temporal node feature (to be predicted).

To be clear, the task is a node-level temporal prediction of a continuous value k steps into the future (where often k>100).
I found this [paper](https://assets.amazon.science/50/90/df9385f840c7b0363febf882a6ad/spatio-temporal-multi-graph-networks-fordemand-forecasting-in-online-marketplaces.pdf) and was wondering if you've implemented anything like it or would be interested in collaborating on its implementation. Additionally, do you know of other methods that could answer this?

**Comment by benedekrozemberczki** [comment]
You could parametrize the edge weights based on edge features with a neural net. From that point it is a vanilla dynamic graph temporal signal problem.
