### ISSUE TITLE
Handling missing data

### ISSUE THREAD

**Issue by vishalmhjn** [benedekrozemberczki/pytorch_geometric_temporal#139]
In the case of multivariate graph time-series, it is common to come across missing data points (e.g., some nodes don't have data some of the time asynchronously). Is there any method implemented to handle the missing data?
Thanks in advance.

**Comment by benedekrozemberczki** [comment]
Dear @vishalmhjn,

You can have binary indicators added to your node feature matrix and replace missing values with zeros.  

Could you star the repo?

Benedek
