### ISSUE TITLE
Tutorial 404s

### ISSUE THREAD

**Issue by jspisak** [benedekrozemberczki/pytorch_geometric_temporal#14]
Hi there..
I was taking a look at the project for consideration for the PyTorch ecosystem and noticed that the tutorial link early on in the readme 404s and takes me to: https://github.com/benedekrozemberczki/pytorch_geometric_temporal/blob/master

<img width="856" alt="Screen Shot 2020-12-06 at 8 36 07 PM" src="https://user-images.githubusercontent.com/11398925/101310045-ad172f80-3802-11eb-83aa-6b30cf89cdb0.png">

**Comment by benedekrozemberczki** [comment]
Dear @jspisak,

I fixed the 404.

Bests,

Benedek

**Comment by jspisak** [comment]
thanks!
