### ISSUE TITLE
Run on cuda 11.1 at Colab

### ISSUE THREAD

**Issue by BaseMax** [benedekrozemberczki/pytorch_geometric_temporal#140]
Hi Benedek,

I am going to use/run this project in colab.

![image](https://user-images.githubusercontent.com/2658040/154988918-f66baffc-23e1-4df2-9d6d-6082faec2037.png)

Does you have a "colab" project which can share to me? I think its really is a good showcase to add colab.

By the way, I am going to run in a colab. and CUDA version 11.1 installed on the colab. Does this project support version 11.1? Since you not mentioned this and just mentioned 11.3.
![image](https://user-images.githubusercontent.com/2658040/154988744-4f331661-e083-4478-ac29-88e279abeda0.png)

Thank you.
Best

**Comment by BaseMax** [comment]
Seems this working with CUDA 11.1 in colab.

#### `nvcc --version`

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Oct_12_20:09:46_PDT_2020
Cuda compilation tools, release 11.1, V11.1.105
Build cuda_11.1.TC455_06.29190527_0
```
![image](https://user-images.githubusercontent.com/2658040/154999263-266f81bf-8591-4c11-be0d-bb4319b5927a.png)

**Comment by benedekrozemberczki** [comment]
@BaseMax That is great. May I ask what is your use case?

**Comment by BaseMax** [comment]
> @BaseMax That is great. May I ask what is your use case?

Thank you @benedekrozemberczki.

```
import torch
from tqdm import tqdm
import torch.nn.functional
import torch.nn.functional as F
from torch_geometric_temporal.nn.recurrent import GConvGRU

class RecurrentGCN(torch.nn.Module):
    def __init__(self, node_features, filters):
        super(RecurrentGCN, self).__init__()
        self.recurrent = GConvGRU(node_features, filters, 2)
        # 100%|██████████| 50/50 [21:05<00:00, 25.30s/it]
        # MSE: 0.7935
        self.linear = torch.nn.Linear(filters, 1)

    def forward(self, x, edge_index, edge_weight):
        h = self.recurrent(x, edge_index, edge_weight)
        h = F.relu(h)
                
        h = self.linear(h)
        return h

model = RecurrentGCN(node_features=14, filters=32)

optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

model.train()

for epoch in tqdm(range(50)):
    for time, snapshot in enumerate(train_dataset):
        y_hat = model(snapshot.x, snapshot.edge_index, snapshot.edge_attr)
        cost = torch.mean((y_hat-snapshot.y)**2)
        cost.backward()
        optimizer.step()
        optimizer.zero_grad()

model.eval()
cost = 0
for time, snapshot in enumerate(test_dataset):
    y_hat = model(snapshot.x, snapshot.edge_index, snapshot.edge_attr)
    cost = cost + torch.mean((y_hat-snapshot.y)**2)
cost = cost / (time+1)
cost = cost.item()
print("MSE: {:.4f}".format(cost))
```

I am going to run other methods on the Wikipedia model. Can you please guide me?

I mean other than GConvGRU.
- GConvLSTM
- GCLSTM
- LRGCN
etc

**Comment by benedekrozemberczki** [comment]
Hi there @BaseMax,

I hope that these can help:

https://github.com/benedekrozemberczki/pytorch_geometric_temporal/tree/master/examples/recurrent

Could you star the repo?

Bests,

Benedek

**Comment by BaseMax** [comment]
I star the repository.

> I hope that these can help:
https://github.com/benedekrozemberczki/pytorch_geometric_temporal/tree/master/examples/recurrent

They programs are for other datasets. I want to check the different methods just on **Wikipedia** dataset.

I want to run different method on Wikipedia dataset, which you presented at the article.
Can you help me?

Source code of that program which you presented in article about Wikipedia dataset not available?

**Comment by BaseMax** [comment]
I mean this table and that data:

![image](https://user-images.githubusercontent.com/2658040/155415861-a2ece088-e1ec-484b-909e-55a5def64413.png)
