### ISSUE TITLE
GCN layers in TGCN

### ISSUE THREAD

**Issue by jiayilong** [benedekrozemberczki/pytorch_geometric_temporal#144]
Hi, I am wondering why we use different GCN layers to calculate X for the update gate, reset gate and candidate hidden state of GRU in the TGCN model? 

In the source code, a GCN layer is created under each GRU gate, i.e., `self.conv_z`, `self.conv_r` and `self.conv_h`, so that there will be three different Xs for calculating these GRU gates and candidate hidden state. 

I understand the X should be the same when calculating GRU gates and candidate hidden state. Can we calculate the X with a GCN layer first, and then feed the same X into a GRU to calculate gates?

Thank you.

**Comment by benedekrozemberczki** [comment]
Dear @jiayilong,

Yes you can do that. Can you star the repo?

Bests,

Benedek
