### ISSUE TITLE
GConvGRU hidden state not passed

### ISSUE THREAD

**Issue by josephenguehard** [benedekrozemberczki/pytorch_geometric_temporal#145]
Hi! I have a similar question as #143: in the `GConvGRU` examples recurrent folder, the hidden state is not passed at all. Would that not harm performance as the hidden state is then always reset to zeros in the for loop?

**Comment by benedekrozemberczki** [comment]
Yes it would, you can set the cell states between the epoch and the sequence iteration loop.

**Comment by josephenguehard** [comment]
Thank you for your quick reply!
