### ISSUE TITLE
Tutorial for creating custom dataset for multiple dynamic graphs?

### ISSUE THREAD

**Issue by johnnytam100** [benedekrozemberczki/pytorch_geometric_temporal#146]
Hi Benedek! 

I wonder if there is a tutorial for creating a custom dataset for multiple dynamic graphs?

I want to follow a code snippet so I can play around to learn how to do that.

Thanks in advance. :)

**Comment by johnnytam100** [comment]
ps More specifically, I want to perform temporal graph classification.

i.e. multiple temporal (dynamic) graphs with each associated with a label, and I want to ingest them into PyG temporal to classify each temporal graph.

**Comment by benedekrozemberczki** [comment]
Dear @johnnytam100,

Did you manage to do this on your own?

Benedek

**Comment by johnnytam100** [comment]
Hi Benedek, hmm... I tried to understand how to do that but had no luck.
If you have an example code snippet on that, please let me know. 
In the meantime, I will leave it behind or try to see if PyG alone works.
Thanks in advance.

**Comment by benedekrozemberczki** [comment]
If you can donate the dataset I can create a tutorial using your dataset and task.

**Comment by johnnytam100** [comment]
Benedek, thank you so much for the offer!!!
Yes, I am 100% willing to donate the dataset.
Let me describe the dataset briefly:
I have ~700 graphs constructed from protein structures, and I will do molecular dynamics simulation on each graph.
Molecular dynamics simulation will generate many snapshots of the original graph (i.e. a time axis is now generated).
Therefore, I will have 700 dynamic graphs.
Besides, each graph is associated with a label.
So the ultimate goal is: to ingest the 700 dynamic graphs into PyG temporal to build a classifier to predict the label.

I will provide you with the dataset in the following format :
`ls -d -1`
```
graph_0001     # one directory contains one dynamic graph
graph_0002
graph_0003
...
```
`ls -1 ./graph_0001/*`
```
```
graph_0001_snapshot_001.p     # networkx objects
graph_0001_snapshot_002.p
graph_0001_snapshot_003.p
...
```
Do you think it is understandable + workable?
Thanks again Benedek!

**Comment by benedekrozemberczki** [comment]
Can you share the dataset by e-mail and some pointers about the task?

**Comment by johnnytam100** [comment]
Hi @benedekrozemberczki , I have just sent you an email. Thanks again.

**Comment by skaudrey** [comment]
@benedekrozemberczki I'm also trying to create custom dataset on graph classification tasks, looking forward to be inspired by your tutorial.

**Comment by benedekrozemberczki** [comment]
@skaudrey Do you have a dataset to share?

**Comment by ZeynepP** [comment]
Is this tutorial created? Could you please share the link?
