### ISSUE TITLE
Deal with no features for some nodes at some time steps

### ISSUE THREAD

**Issue by Guigo95** [benedekrozemberczki/pytorch_geometric_temporal#149]
Hi,

Thank you very much for this great work!

I was wondering how to deal with a dynamic graph for which some nodes appear or disappear. 
Let's say I have 3 nodes [0 1 2] and three time steps with these graphs:
t1 : 0 1-2
t2 : 0-1-2
t3 : 0-1 2
At t1, node 0 does not exist, i.e. I have no features. Same for node 2 at t3. In fact, I could fill in the features of node 0 at t0 with nan, as well as those of node 2 at t3.
In the only dynamic graph dataset provided (TwitterTennisDatasetLoader), the features exist for all nodes at every point in time, even if there is no connection.

Thanks in advance !

**Comment by Guigo95** [comment]
in issue #139 you said 'You can have binary indicators added to your node feature matrix and replace missing values with zeros'. So you just add a new feature for each node filled with one when the node exists and 0 if not?

**Comment by vishalmhjn** [comment]
This was also the intention in issue #139. I am not sure about this approach if in a given context for a specific feature "zero" means something else.

**Comment by doGregor** [comment]
Hi,

I guess you should always use the same set of nodes in the same order for every graph you generate (even if some nodes are not present in different snapshots in reality), the shape of nodes stays the same. To avoid that non present nodes are considered during message passing in a specific snapshots, you set their complete feature vector to zero. During matrix multiplication they won't have an influence then.

For your example that means (assuming that you have a 3-dimensional feature vector at each node and when a node is present its features are `[1,1,1]`):
`t1: 0 1-2` where `0 = [0,0,0], 1=[1,1,1], 2=[1,1,1]`
`t2: 0-1-2` where `0 = [1,1,1], 1=[1,1,1], 2=[1,1,1]`
`t3: 0-1 2` where `0 = [1,1,1], 1=[1,1,1], 2=[0,0,0]`

Same applys to incomplete features: just set those you don't have to zero, e.g.: `2=[1,0,1]` if feature 2 of node 2 is not present at a specific snapshot.

Hope this helps! Feel free to correct me if I got something wrong :-)
Gregor

**Comment by Guigo95** [comment]
Thanks @doGregor, I'll try it this way, but the issue raised by @vishalmhjn, can clearly be harmfull in some case !
