### ISSUE TITLE
Minibatch training over different DynamicGraphDiscreteSignals iterators?

### ISSUE THREAD

**Issue by coballejr** [benedekrozemberczki/pytorch_geometric_temporal#15]
Hello,

Is there a straightforward way to use diagonal block matrix-based batching with a list of different DynamicGraphDiscreteSignals iterator objects? 

For context, each DynamicGraphDiscreteSignals iterator represents a different trajectory of a dynamical system.

Thanks,
Chris

**Comment by benedekrozemberczki** [comment]
No, you could batch when you create the object. Is it complicated?

**Comment by coballejr** [comment]
That should work.

Thank you,
Chris

**Comment by benedekrozemberczki** [comment]
Dear @coballejr,

1. Do you plan to write a paper? We would appreciate it if you would cite the library.
2. Can you open-source the dataset? If yes, we can add you as a co-author to the PTG paper.

Bests,

benedek

**Comment by coballejr** [comment]
@benedekrozemberczki,

     1. Yes, but we're still very early in the process. We'll be sure to cite your work.
     2. I'll pass it your way once I'm done preprocessing.

Thank you,
Chris

**Comment by smorad** [comment]
I'm also interested in this. Could you explain "batch when you create object"? Do you mean make `feature.shape` `BxNxK` instead of `NxK`?

**Comment by benedekrozemberczki** [comment]
No. I mean creating a block diagonal matrix of the adjacency matrices.
