### ISSUE TITLE
Create a custom dataset

### ISSUE THREAD

**Issue by polkadot21** [benedekrozemberczki/pytorch_geometric_temporal#157]
Thanks for the package, I appreciate it a lot!
I have a question about how to create a custom dataset. 

I went through the source code, e. g. `PedalMeDatasetLoader` uses a link to the `pedalme_london.json`  file:

`def __init__(self):
        self._read_web_data()

    def _read_web_data(self):
        url = "https://raw.githubusercontent.com/benedekrozemberczki/pytorch_geometric_temporal/master/dataset/pedalme_london.json"
        self._dataset = json.loads(urllib.request.urlopen(url).read())
`

This file already contains `X`, `edges`, and `weights`.
Given a `pandas` dataset with sequential data and geolocation of nodes (Latitude and Longitude):

https://colab.research.google.com/drive/1D7kDsImqSHzS482oOeKVXwJ1cJ_2B6Lp#scrollTo=5EHH1LIKOxJb&line=1&uniqifier=1

how can I create a .json file needed to create `StaticGraphTemporalSignal`?
Any help would be highly appreciated.

**Comment by SherylHYX** [comment]
The .json file is storing a dict in your example and you could do something similar.

**Comment by polkadot21** [comment]
> The .json file is storing a dict in your example and you could do something similar.

Thank you for your response!
Let me reformulate my question. How can I create edges and weights given geospatial data (Latitude and Longitude) as I provided via the link above?

**Comment by SherylHYX** [comment]
It seems to me that I do not have permission to access the file unfortunately.

However, based on your question: this depends on what you would like to act as nodes. For example, you could pick some locations as nodes and the inverse distance (or some form of similarity) between nodes as edge weights. Then you might end up with a complete graph, but then you could either set up a threshold for the edge weight value (zero-out all values underneath) or just keep the top edges.

Hope that my answer this time provides some useful information!

Best,
Yixuan He (Sheryl)
