### ISSUE TITLE
Any examples of MTGNN and GMAN based on traffic dataset like METRLA

### ISSUE THREAD

**Issue by SonghuaHu-UMD** [benedekrozemberczki/pytorch_geometric_temporal#158]
Hello!

Thanks for providing this amazing tool! I am trying to work with some models like MTGNN and GMAN. They seem to have complex inputs and parameters settings. And I always meet some errors when using them on traffic datasets like METRLA.

Is there any example of using MTGNN and GMAN based on traffic dataset like METRLA, just like the current examples in /notebooks/[a3tgcn_for_traffic_forecasting.ipynb](https://github.com/benedekrozemberczki/pytorch_geometric_temporal/blob/master/notebooks/a3tgcn_for_traffic_forecasting.ipynb)

Thanks so much!

**Comment by SherylHYX** [comment]
Hello Songhua,

Have you ever generated initial SE and TE for GMAN?

As for MTGNN, it is originally designed for data without a given graph structure, but simply multivariate time series.

Could you show what you have tried and what errors you have encountered?

Best,
Yixuan He (Sheryl)
