### ISSUE TITLE
Extreme RAM consumption by multilayer models

### ISSUE THREAD

**Issue by funbotan** [benedekrozemberczki/pytorch_geometric_temporal#159]
Hi Benedek! First of all, thank you for this project, I hope it has a bright future ahead.
My issue is with building deep/multi-layer models out of Recurrent Graph Convolutional Layers. There are no examples of it in the repo (or anywhere else on the internet as far as I searched), so I might be doing something wrong. [Here is my project.](https://gitlab.com/funbotan/transense-model-comparison/-/blob/master/lib/rgcnn.py) Now, what I observe when running this code is that RAM utilization goes up nearly exponentially with the number of RGC layers. Of course, most of it ends up in swap, making the training process too slow to be viable. This does not appear to be a memory leak, since most of the memory is not used by Python objects, but rather internally by PyTorch. Have you encountered this issue and is there a way to fix it?

**Comment by SherylHYX** [comment]
For another, during evaluation, you could use "with torch.no_grad()". See for example [here](https://datascience.stackexchange.com/questions/32651/what-is-the-use-of-torch-no-grad-in-pytorch).

**Comment by SherylHYX** [comment]
> Thank you, I see how that would help. However, won't that also discard the temporal data correlations?

You could see from [our paper](https://dl.acm.org/doi/abs/10.1145/3459637.3482014?casa_token=LNfOZAGLtuQAAAAA%3A36ll2iy90i5xq3W78PqiByF1zbMUpbYw4n7PtT4DYAxxWVFu7vK_2RINbW-TCtAcVTDgTNNLnLb8bQ) that for some input e.g. Wikipedia Math, using the incremental backprop regime actually does leads to better performance than the cumulative one. This is similar to using a mini-batch for SGD compared to using the full batch.

**Comment by funbotan** [comment]
Well, this did solve the memory consumption problem. Training time has only marginally improved, though, due to the frequent backward passes. I'll try searching for a compromise later. Can't really compare the performance, because the previous configuration never even finished training.
Do you think this problem is inherent to GCNs or is it just an implementation issue?

**Comment by SherylHYX** [comment]
Good that it helps! It is related to how you do backprop for temporal snapshots but not a GCN issue.
________________________________

**Comment by funbotan** [comment]
Alright, I'll close the issue for the time being, but very much hope that someone comes up with a better solution down the line. Thank you very much @SherylHYX
