### ISSUE TITLE
Model choice to handle edge_attr with multiple features

### ISSUE THREAD

**Issue by rperera12** [benedekrozemberczki/pytorch_geometric_temporal#161]
Hello, 
Thank you for creating this library, it is very helpful and straight forward to use.
I came across this question recently when using the A3TGCN model...
I have a graph with multiple edge attributes rather than a single edge attribute.
Is there a model available that can handle this case? 
I have thought of using a linear layer to make num_edge_features ---> 1 [ e.g., nn.Linear(num_edge_features,1).relu() ] 
But maybe there is a model available that can handle this case?

**Comment by benedekrozemberczki** [comment]
Yes you could have similar models, it should work.

**Comment by benedekrozemberczki** [comment]
@rperera12 could you star the repo?

**Comment by Tiantiansayhi** [comment]
hello, Roberto, I also have a problem with multiple edge attributes which want to be solved by A3TGCN or other temporal GCN. Did you slove this problem, and what's the meaning of using a linear layer for it?  I am interested in it.
