### ISSUE TITLE
Missing documentation about introductory example PyTorch lightning

### ISSUE THREAD

**Issue by DanielPerezJensen** [benedekrozemberczki/pytorch_geometric_temporal#165]
On the [index page](https://pytorch-geometric-temporal.readthedocs.io/en/latest/index.html?highlight=lightning#pytorch-geometric-temporal-documentation) of this package, it is stated that: 

"The package interfaces well with [Pytorch Lightning](https://pytorch-lightning.readthedocs.io/) which allows training on CPUs, single and multiple GPUs out-of-the-box. Take a look at this introductory example of using PyTorch Geometric Temporal with Pytorch Lighning."

However, below there is no such introductory example. Is this supposed to be added still, or am I missing something?

**Comment by amorehead** [comment]
Hi, @DanielPerezJensen. It looks like this link may take you to the PyTorch Lightning tutorial you asked about: https://github.com/benedekrozemberczki/pytorch_geometric_temporal/blob/master/examples/recurrent/lightning_example.py
