### ISSUE TITLE
Moving HeteroGCLSTM to cuda device for GPU training

### ISSUE THREAD

**Issue by DanielPerezJensen** [benedekrozemberczki/pytorch_geometric_temporal#166]
I am trying to train a HeteroGCLSTM model using my GPU for faster training. However it seems that this is not possible when using the standard `.to` function in PyTorch. When I move my model and data to the gpu, as in this example:

```python
device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
model = model.to(device)

model.train()

for epoch in (pbar := tqdm(range(5))):
    
    cost = 0
    h, c = None, None
    
    for time, snapshot in tqdm(enumerate(train_dataset), desc="data", total=total):
        snapshot = snapshot.to(device)
        y_hat, h, c = model(snapshot.x_dict, snapshot.edge_index_dict, h=h, c=c)
        
        y_hat = y_hat.cpu()
        y_true = snapshot.y_dict["measurement"].cpu()
        
        cost = cost + torch.mean((y_hat - y_true) ** 2)

    cost = cost / (time + 1)

    pbar.set_description(f"MSE: {round(cost.item(), 3)}")
    cost.backward()
    optimizer.step()
    optimizer.zero_grad()
```

I get the following error:

```bash
..........................
    110 def _calculate_input_gate(self, x_dict, edge_index_dict, h_dict, c_dict):
--> 111     i_dict = {node_type: torch.matmul(X, self.W_i[node_type]) for node_type, X in x_dict.items()}
    112     i_dict = {node_type: I + self.conv_i(h_dict, edge_index_dict)[node_type] for node_type, I in i_dict.items()}
    113     i_dict = {node_type: I + self.b_i[node_type] for node_type, I in i_dict.items()}

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument mat2 in method wrapper_mm)
```

I can verify that the snapshot is indeed on the GPU, so it seems that the weight matrix `W_i[node_type]` is not on the GPU. Is this supposed to be the case, or am I supposed to move the model to the GPU in another way? If so, what is the best way to do this?

How I am thinking of doing it now is to move each weight matrix contained within the dictionary to GPU "manually" but given the large amount of weight and bias terms this might be clumsy.

**Comment by doGregor** [comment]
Hi @DanielPerezJensen ,

you are right, currently you can't run the model (or easily transfer it) on a GPU. The only way to do it at the moment is moving all parameters to your GPU, e.g.:
```python
self.W_i = {node_type: Parameter(torch.Tensor(in_channels, self.out_channels)).to('cuda')
            for node_type, in_channels in self.in_channels_dict.items()}
```
You have to do it for all values in `W_i`, `b_i`, `W_f`, `b_f`, `W_c`, `b_c`, `W_o`, `b_o` as well as `h_dict` and `c_dict`.

Best,
Gregor
