### ISSUE TITLE
perform edge regression

### ISSUE THREAD

**Issue by tliu1023** [benedekrozemberczki/pytorch_geometric_temporal#167]
Hi,

I have a edge regression problem that the input is node feature X.shape = (N, Nx). The output is on the edge y.shape = (E, 1). For link prediction problem we can compute the inner product of node feature embedding H@H.T to predict the link existence. But I'm not sure how to perform a  link regression in a similar way. I'm wondering do we have some existing networks that perform link regression? Thank you!

**Comment by benedekrozemberczki** [comment]
Dear @tliu1023 ,

Thank for the question! Could you star the repo?

You could concatenate the node representations at the edge endpoints and pass it through a feed forward net trained jointly with the temporal GCN. 

Bests,

Benedek
