### ISSUE TITLE
Combining multiple graph files into one StaticGraphTemporalSignal

### ISSUE THREAD

**Issue by eduardoftdo** [benedekrozemberczki/pytorch_geometric_temporal#169]
Hi everyone. I'm working on a project with hand landmark data similar to the one used in the [MTMDatasetLoader](https://github.com/benedekrozemberczki/pytorch_geometric_temporal/blob/master/torch_geometric_temporal/dataset/mtm.py). 

However, I have multiple files where each file has graph representations over time, but only one target per file (differently from MTM where the target changes over time). 

Is there any example of using this dataset loader to iterate over those multiple files and create a StaticGraphTemporalSignal to train a STGCN?

Thanks in advance and congratulations on the library!

**Comment by benedekrozemberczki** [comment]
https://user-images.githubusercontent.com/7347296/34198790-eb5bec96-e56b-11e7-90d5-157800e042de.png

**Comment by zarif98sjs** [comment]
Hey @eduardoftdo , were you able to do that? I am trying to do something similar to you but can't seem to properly format the data. Also couldn't find any proper example of using `StaticGraphTemporalSignalBatch`.
