### ISSUE TITLE
Add custom datasets

### ISSUE THREAD

**Issue by johnny12150** [benedekrozemberczki/pytorch_geometric_temporal#17]
Is there a tutorial to add custom datasets?

**Comment by benedekrozemberczki** [comment]
Hi there @johnny12150,

I am happy to write a tutorial if you are willing to open-source the dataset with us.

Bests,

Benedek

**Comment by johnny12150** [comment]
Actually, I am using some open-source datasets with given timestamps and intend to transform them into evolving datasets.

**Comment by benedekrozemberczki** [comment]
May I ask which are these datasets?

**Comment by johnny12150** [comment]
Since I am focusing on the research of recommendation systems, those datasets are Amazon, Nowplaying or Tmall, etc...

- [Tmall](https://tianchi.aliyun.com/dataset/dataDetail?dataId=47)
- [Nowplaying](https://dbis.uibk.ac.at/node/263#nowplaying)

**Comment by ArashJavan** [comment]
Hi and happy new year,

thanks for this great repo. I am working on a time-series dataset and would like to know:

1) Does pyGeoTemp supports multidimensional time-series. AFAIK the Chickenpox dataset you provide is dim=(#num-nodes=20, #time-stamps=4). But my datasets dim=(seq-lenth, #nodes, #numfeatures). How can I create a multidim temporal dataset?

2) Which graph supports this kind of data, i.e. takes as input data with  dim=(seq-lenth, #nodes, #numfeatures) or even better  dim=(batch-size, seq-lenth, #nodes, #numfeatures)?

Thanks
Arash
