### ISSUE TITLE
Tensor dimensionality mismatch in HeteroGCLSTM

### ISSUE THREAD

**Issue by DrKleiber** [benedekrozemberczki/pytorch_geometric_temporal#170]
Hello,

I'm working on a node-level prediction problem using HeteroGCLSTM. I followed the METRLADatasetLoader as an example to creat my dataset.

My feature_dict is like this snapshot.x_dict['a'].size() = 11x5x50, dim 0 is num_nodes, dim 1 is num_features, dim 2 is time_steps.

When I use HeteroGCLSTM, I had the following error 

`    i_dict = {node_type: torch.matmul(X, self.W_i[node_type]) for node_type, X in x_dict.items()}

RuntimeError: mat1 and mat2 shapes cannot be multiplied (55x50 and 5x64)`

I wonder is there a fix to this? Thank you in advance!

**Comment by doGregor** [comment]
Hi,

a snapshot is a graph at time t, so dimension 2 of your `x_dict` should not be in the feature set but represents the number of snapshots. So instead of your current `x_dict` you should have 50 snapshots where each has `x_dict['a'].size() = 11x5`.

Best,
Gregor

**Comment by DrKleiber** [comment]
> Hi @doGregor thank you for the explanation. For my problem, I need to use multiple previous time steps to predict the future state, similar to many problems like traffic or covid cases prediction. I wonder does the current HeteroGCLSTM support this problem? If yes, how can I design my input graph?
