### ISSUE TITLE
community detection using PyG temporal

### ISSUE THREAD

**Issue by MGermanos** [benedekrozemberczki/pytorch_geometric_temporal#173]
Hello!

Is it possible to perform community detection using this library? 
I have a temporal dataset where the nodes have a binary feature, and this feature can flip from 0 to 1 at a given time and then flip back to 0. I want to figure out the clusters of nodes most likely to flip together.

So as a final model, I would like to input a node and get the set of nodes that will flip with it as output.

I apologize if my question is banal, I am new to this field.

**Comment by benedekrozemberczki** [comment]
Do you have labeled data?

**Comment by MGermanos** [comment]
I do!
I have uploaded one example of the dataset [here](https://drive.google.com/file/d/1Bj8LfqyglEGdN63ohjCSkzJUpEdvJXfY/view?usp=sharing).
every line of the file shows which nodes flipped to 1 at this given time.

**Comment by benedekrozemberczki** [comment]
Closing for now until you have data.
