### ISSUE TITLE
Suggestion: storing the downloaded dataset somewhere

### ISSUE THREAD

**Issue by diningphil** [benedekrozemberczki/pytorch_geometric_temporal#175]
Hi, 
I noticed that a dataset loader like the `ChickenpoxDatasetLoader` does not store the dataset on disk for faster, connection-less retrieval. This can create issues whenever one cannot temporarily access the Github repository where such files are saved. It would be a cool feature to have the dataset stored on disk in a similar fashion to Pytorch Geometric.

Thanks for the repo and best regards,
Federico

**Comment by benedekrozemberczki** [comment]
Hi there,

I will look into this - currently I am a bit overwhelmed with other things :).

Bests,

Benedek

**Comment by benedekrozemberczki** [comment]
Closing for now,
