### ISSUE TITLE
Why does the A3T-GCN model's predicted curve never match the real curve?

### ISSUE THREAD

**Issue by Meow10** [benedekrozemberczki/pytorch_geometric_temporal#179]
The code for A3TGCN:
```
class TemporalGNN(torch.nn.Module):
    def __init__(self, node_features, periods):
        super(TemporalGNN, self).__init__()

        self.tgnn = A3TGCN(in_channels=node_features, 
                           out_channels=32, 
                           periods=periods)

        self.linear = torch.nn.Linear(32, periods)

    def forward(self, x, edge_index):
        """
        x = Node features for T time steps
        edge_index = Graph edge indices
        """
        h = self.tgnn(x, edge_index)
        h = F.relu(h)
        h = self.linear(h)
        return h

model = TemporalGNN(node_features=2, periods=12).to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=args.learning_rate, weight_decay=args.weight_decay)
scheduler = torch.optim.lr_scheduler.ExponentialLR(optimizer, gamma=0.9)

model.train()

minl = 1e5
print("Running training...")
for epoch in range(200): 
    loss = 0
    step = 0
    for snapshot in train_dataset:
        snapshot = snapshot.to(device)
        y_hat = model(snapshot.x, snapshot.edge_index)
        loss = loss + torch.mean((y_hat-snapshot.y)**2) 
        step += 1
        if step > subset:
          break

    loss = loss / (step + 1)
    loss.backward()
    optimizer.step()
    optimizer.zero_grad()
```

On the dataset METR-LA, the predicted curve is smooth and very different from the real curve. 
![result1](/../../../../Meow10/Meow10/blob/main/A9B177D0-30E2-40CD-A3AE-D71EDE7704F9.png)
After parameter tuning:
![result2](/../../../../Meow10/blob/main/46269192-FF68-4AC3-829D-C27C76E08D90.png)

**Comment by Doradx** [comment]
Maybe I found the reason recently. https://github.com/benedekrozemberczki/pytorch_geometric_temporal/issues/204

**Comment by aurorarossi** [comment]
Hi! I recently wrote [this tutorial](https://carlolucibello.github.io/GraphNeuralNetworks.jl/dev/tutorials/introductory_tutorials/traffic_prediction/#Traffic-Prediction-using-recurrent-Temporal-Graph-Convolutional-Network) about traffic prediction and the [A3T-GCN model](https://github.com/CarloLucibello/GraphNeuralNetworks.jl/blob/e3019dd33add3e97bdf116b02c3e17cc439f9047/src/layers/temporalconv.jl#L151), maybe you can find it useful even though it is written in the Julia programming language.
