### ISSUE TITLE
Custom Dataset Multidimensional Timeseries

### ISSUE THREAD

**Issue by ArashJavan** [benedekrozemberczki/pytorch_geometric_temporal#19]
Hi and happy new year,

thanks for this great repo. I am working on a time-series dataset and would like to know:

1) Does pyGeoTemp supports multidimensional time-series. AFAIK the Chickenpox dataset you provide is dim=(#num-nodes=20, #time-stamps=4). But my datasets dim=(seq-lenth, #nodes, #numfeatures). How can I create a multidim temporal dataset?

2) Which graph supports this kind of data, i.e. takes as input data with  dim=(seq-lenth, #nodes, #numfeatures) or even better  dim=(batch-size, seq-lenth, #nodes, #numfeatures)?

Thanks
Arash

**Comment by benedekrozemberczki** [comment]
The data iterator which we defined supports this, please try it out.

**Comment by gbastiandillo** [comment]
Hello, 
@benedekrozemberczki  do you have any example of how to use an input with size = dim=(seq-lenth, #nodes, #numfeatures) ? 
I'd really appreciate that, I searched in many forums, but didn't find information.

@ArashJavan , did u get any example at the end?
Thanks,
