### ISSUE TITLE
The usage difference between torch.nn.LSTM() and torch_geometric_temporal.nn.conv.GCLSTM()?

### ISSUE THREAD

**Issue by xiaochehe** [benedekrozemberczki/pytorch_geometric_temporal#2]
Hi, I want to use  torch_geometric_temporal.nn.conv.GCLSTM() in my project and take the place of  torch.nn.LSTM(). But I do not know how to do. I want to know the input and output, or other things that are different between torch.nn.LSTM() and torch_geometric_temporal.nn.conv.GCLSTM().

**Comment by benedekrozemberczki** [comment]
The read the docs is quite helpful, it has everything about the data types needed and references the papers. Could you star the repo and hit the follow button?

**Comment by benedekrozemberczki** [comment]
Added an example.

Benedek

**Comment by xiaochehe** [comment]
> 
> 
> Added an example.
> 
> Benedek

That helps me  a lot, Thank you!
