### ISSUE TITLE
GConvGRU error using CUDA

### ISSUE THREAD

**Issue by ArashJavan** [benedekrozemberczki/pytorch_geometric_temporal#20]
Hi,

in the "GConvGRU"-class the hidden state is created regardless of the device type fo the input.
See [here](https://github.com/benedekrozemberczki/pytorch_geometric_temporal/blob/master/torch_geometric_temporal/nn/recurrent/gconv_gru.py#L102).

**Comment by benedekrozemberczki** [comment]
What do you recommend?

**Comment by ArashJavan** [comment]
Maybe something like this:

`    def _set_hidden_state(self, X, H):
        if H is None:
            H = torch.zeros(X.shape[0], self.out_channels).to(X.device)
        return H`

**Comment by benedekrozemberczki** [comment]
Okay, all of the hidden state and cell state definitions were redefined.
