### ISSUE TITLE
[A3TGCN] This implementation is different with the original paper.

### ISSUE THREAD

**Issue by Doradx** [benedekrozemberczki/pytorch_geometric_temporal#204]
This is a great geometric temporal framework.
But there are issues when I read the source code of A3TGCN and A3TGCN2.
I read the source code from this repository (based on PyTorch) and compared it with the [original paper](https://www.mdpi.com/2220-9964/10/7/485) and [original code (based on TensorFlow)](https://github.com/lehaifeng/T-GCN/blob/master/A3T-GCN/A3T-GCN.py).
Then I found that the attention modules were different in detail.
For the original version, the context vector Ct was calculated using the MLP and the hidden states of T-GCN, and <img src="https://render.githubusercontent.com/render/math?math=e_i"> should be determined as follows:
![description of the attention module](https://user-images.githubusercontent.com/23170065/208972307-00e70242-6bbf-4404-88bb-04edf2c1e47d.png)
and the original source code:
https://github.com/lehaifeng/T-GCN/blob/e21fb99a5c56fdf667a4ff7a9c8236761f7377f8/A3T-GCN/A3T-GCN.py#L90-L109

But, this implementation just used the parameters self._attention to represent <img src="https://render.githubusercontent.com/render/math?math=e_i">,  as follows: 
https://github.com/benedekrozemberczki/pytorch_geometric_temporal/blob/e43e95d726174574eeae32ad8c4670631fd0a58d/torch_geometric_temporal/nn/recurrent/attentiontemporalgcn.py#L49
https://github.com/benedekrozemberczki/pytorch_geometric_temporal/blob/e43e95d726174574eeae32ad8c4670631fd0a58d/torch_geometric_temporal/nn/recurrent/attentiontemporalgcn.py#L74
https://github.com/benedekrozemberczki/pytorch_geometric_temporal/blob/e43e95d726174574eeae32ad8c4670631fd0a58d/torch_geometric_temporal/nn/recurrent/attentiontemporalgcn.py#L76-L78

Obviously, this is a modified version of A3TGCN, and the attention module has no relationship with the hidden state of the T-GCN module.
In my opinion, this modification is significant, and should be marked in docs and related source code, or should be modified to be consistent with the original paper.

Thanks sincerely for your dedication!
Best!

**Comment by CarloLucibello** [comment]
why this was closed? The original paper is poorly written and hard to decrypt, but the implementation here is certainly wrong.
