### ISSUE TITLE
Potential discrepancy between the code and the paper?

### ISSUE THREAD

**Issue by tpjoe** [benedekrozemberczki/pytorch_geometric_temporal#21]
Hi, I'm new to this so I am probably misunderstanding somethings. The function [GCLSTM](https://pytorch-geometric-temporal.readthedocs.io/en/latest/_modules/torch_geometric_temporal/nn/recurrent/gc_lstm.html) was adapted from the paper [C-LSTM: Graph Convolution Embedded LSTM for Dynamic Link Prediction](https://arxiv.org/abs/1812.04206), but there are couple formulations in the code that are different from those stipulated in the paper. These include:

1. Multiplication of the cell's weights to node features instead of the adjacency matrix, and
2. Using the edge index at time _t_ instead of _t-1_

Using input gate as an example where the paper formulated it as: 

<img src="https://latex.codecogs.com/svg.latex?\Large&space;i_{t}=\sigma(W_{i}A_{t}+\sum_{k=0}^{n}\theta_{hki}T_{k}\left(\tilde{L}_{t-1}\right)h_{t-1}+b_{i})" />

But the code has it as:

> `I = torch.matmul(X, self.W_i)` 
> `I = I + self.conv_i(H, edge_index, edge_weight)`

where X is the node feature matrix.

I'm sure I'm missing somethings, and would appreciate your help to better understand this. Thanks!

**Comment by benedekrozemberczki** [comment]
Dear Thanaphong,

You can feed in earlier edge snapshots and you can represent the next step
adjacency matrix as X. Do you get what I mean?

I believe it answers both of your questions.

Could you star the repo and hit follow?

Benedek

**Comment by tpjoe** [comment]
Yes definitely, followed and starred, this is an awesome repo. 

I'm sorry but I am still a bit confused. From your response, yup I guess I could do that, but then is there any reason why X is defaulted to node features in the manual? To be honest, using node features as X actually makes more sense to me be because otherwise there wouldn't be anywhere in the calculation to account for node features, which seems strange, I just don't get why the paper formulated it that way.

**Comment by benedekrozemberczki** [comment]
The paper wants to solve a link prediction problem, when you have no node features based on my understanding as far as I remember. Generally speaking the method proposed in the paper is not really suitable in my opinion to solve that problem.

**Comment by benedekrozemberczki** [comment]
(Not every paper on ArXiv is a good paper.)

**Comment by tpjoe** [comment]
Ahh I see. Thank you!
