### ISSUE TITLE
Does the dynamic graph support changes in the number of nodes in different snapshots? 

### ISSUE THREAD

**Issue by NinaMathiasen** [benedekrozemberczki/pytorch_geometric_temporal#215]
Hi, I am new to this library, and I have a question about the dynamic graphs. 

I am working with a dynamic graph with a temporal signal (class: "DynamicGraphTemporalSignal"). This means that I have different edges (and edge weights) for each snapshot, but I also have some snapshots, where there are nodes (and thereby also targets) which are not present at all in the graph. I am unsure, if this is supported by the library? 

The "Covid19 England" dataset which is mentioned in the original paper is quite similar to my dataset (except that the number of targets and nodes seem to be the same in each snapshot). When I look at the data structure in this dataset, there is nothing which denotes that a specific target is associated to a specific node; the targets are just a list for each snapshot. Therefore it seems to me that the underlying assumption is that all nodes are present at each snapshot.

Also, the dynamic graph with a temporal signal which is illustrated in figure 1 in the paper, is only shown to have dynamic edges and not dynamic nodes, and this leads me to think that having dynamic nodes is not supported. Is this correct?

Thank you for the great library!

**Comment by aurorarossi** [comment]
Hi, I had the same doubt, but in [this paper](https://dl.acm.org/doi/pdf/10.1145/3459637.3482014) which presents the library, it is clear that nodes are not dynamic.
