### ISSUE TITLE
Attribute issue in DynamicTemporalSignal: torch.dtype.kind

### ISSUE THREAD

**Issue by NadineAngermeier** [benedekrozemberczki/pytorch_geometric_temporal#223]
Hello,

I have created a DynamicTemporalSignal dataset which takes torch tensors e.g. for the target.

Within the DynamicTemporalSignal implementation, I run into the error 'torch.dtype' object has no attribute 'kind', which is triggered in the get_target funciton, in the code fragment  'self.targets[time_index].dtype.kind == "f"'. 
In the example data, they have the same datatype, but not multiple targets. 

Could you please help me on how I could resolve the issue? Thank you very much!

My code can be found here:
https://github.com/NadineAngermeier/OPF-PyGTemp

**Comment by cl19951225** [comment]
Hi Nadine,

I've encountered the same issue as you have. Could you please let me know how you fix it? Many thanks!

**Comment by SamerMakni** [comment]
Hello @NadineAngermeier and @cl19951225 

The issue can be easily fixed if you ensure that the objects you are passing to `DynamicGraphTemporalSignal` are NumPy arrays and not tensors, lists, or other data types.

Therefore @NadineAngermeier this is how you should update your code:
```
for timeInterval in range(numGraph):
    timestamp = pd.Timestamp(timestamps[timeInterval])
    source, target = sourceNodes(timestamp)
    
    edge_indices.append(np.array([source, target], dtype=np.long))
    features.append(np.array(nodeAttributes(timestamp), dtype=np.float32))  # (P_D, c, h, P_G_min, P_G_max)
    targets.append(np.array(solAttributes(timestamp), dtype=np.float32))
    edge_weights.append(np.array(edgeAttributes(timestamp), dtype=np.float32))  # (B, Pmax)
```

It should work now!
