### ISSUE TITLE
StaticHeteroGraphTemporalSignalBatch

### ISSUE THREAD

**Issue by MicheleSodano** [benedekrozemberczki/pytorch_geometric_temporal#228]
Hi, I am trying to implement a Hetero Spatial-Temporal GNN which uses HeteroConv with two SAGEConv layers to generate the embedding of nodes in each snapshot, then concatenate the node embeddings from all snapshots, and use a custom 1D ResNet to predict the target value of a specific node type. 
I am using StaticHeteroGraphTemporalSignal to convert several StaticHeteroGraphs created using Networkx (DiGraph) into HeteroData objects.

How can I efficiently create a dataloader to train a heteroGNN model over multiple snapshots?

Can I get an example of how to use StaticHeteroGraphTemporalSignalBatch to create batches of 120 snapshots for a StaticHeteroGraph that contains 8760 snapshots in total?

Additionally, Is there a way to train using batches and multiple StaticHeteroGraphs when the edge_index_dict is different from Graph to Graph?

**Comment by gbastiandillo** [comment]
Hi @MicheleSodano, did you get any example of StaticHeteroGraphTemporalSignalBatch?
