### ISSUE TITLE
is there any example for network traffic prediction?

### ISSUE THREAD

**Issue by smileatl** [benedekrozemberczki/pytorch_geometric_temporal#229]

**Comment by aurorarossi** [comment]
Hi! I recently wrote [this tutorial](https://carlolucibello.github.io/GraphNeuralNetworks.jl/dev/tutorials/introductory_tutorials/traffic_prediction/#Traffic-Prediction-using-recurrent-Temporal-Graph-Convolutional-Network) about traffic prediction, maybe you can find it useful even though it is written in the Julia programming language.
