### ISSUE TITLE
Not able to converge GNN for MontevideoBus Dataset

### ISSUE THREAD

**Issue by UnbeatableOne** [benedekrozemberczki/pytorch_geometric_temporal#230]
Hi,

Thank you for this wonderful library. I have tried with various architectures available in the library to converge the MSE for the above dataset. Can you please provide a working example where it converges properly ?

**Comment by OscarLlorente** [comment]
Why is this being closed? Is it solved? Because it has happened to me the same with windmill dataset in issue https://github.com/benedekrozemberczki/pytorch_geometric_temporal/issues/217
