### ISSUE TITLE
About yhat shape

### ISSUE THREAD

**Issue by seoyeonc** [benedekrozemberczki/pytorch_geometric_temporal#231]
Hi,

I have a question about the example codes.

I can see the introduction of your website. You used a ChickenpoxDataset for the example and wrote down the following:

y_hat = model(snapshot.x, snapshot.edge_index, snapshot.edge_attr)
cost = cost + torch.mean((y_hat-snapshot.y)**2)

In this code, I checked the shape of y_hat, snapshot.y, and y_hat-snapshot.y.
And this is the result.

y_hat   torch.Size([20, 1])
snapshot.y     torch.Size([20])
y_hat-snapshot.y   torch.Size([20,20])
<img width="500" alt="image" src="https://github.com/benedekrozemberczki/pytorch_geometric_temporal/assets/81500714/6c9bae77-53e1-4daa-a77c-a0bd9c4af46d">

Here is my question. Doesn't it have to 'y_hat' be the same shape as snapshot.y?
If we want to compare the y_hat from the model with the values y, the same shape is appropriate to evaluate.
Like this:

y_hat = model(snapshot.x, snapshot.edge_index, snapshot.edge_attr).reshape(-1)
        cost = cost + torch.mean((y_hat-snapshot.y)**2)

If the shape of y_hat changes to as same as snapshot.y,
The result is like this:

y_hat   torch.Size([20])
snapshot.y     torch.Size([20])
y_hat-snapshot.y   torch.Size([20])
<img width="569" alt="image" src="https://github.com/benedekrozemberczki/pytorch_geometric_temporal/assets/81500714/531817ce-0beb-40b9-9fff-382c43ca7b47">

**Comment by SimonPop** [comment]
Hi! 
I think this is currently being fixed by the following pull request: https://github.com/benedekrozemberczki/pytorch_geometric_temporal/pull/233 😄
