### ISSUE TITLE
Multidimensional edge features 

### ISSUE THREAD

**Issue by Alessiobrini** [benedekrozemberczki/pytorch_geometric_temporal#232]
Is it possible that none of the models implemented accepts multidimensional edge features or more general edge features? I see just the edge weights argument in each forward method implemented. Can someone help me clarify this?

**Comment by SimonPop** [comment]
Hi!

I think you are right, at the moment there does not seem to be any model taking edge features as a possible input to their `forward` method.

Actually, the only layers currently in use from PyG I could find are:
- [GCNConv](https://pytorch-geometric.readthedocs.io/en/latest/generated/torch_geometric.nn.conv.GCNConv.html?highlight=GCNConv#torch-geometric-nn-conv-gcnconv)
- [ChebConv](https://pytorch-geometric.readthedocs.io/en/latest/generated/torch_geometric.nn.conv.ChebConv.html?highlight=ChebConv#torch-geometric-nn-conv-chebconv)
- [SageConv](https://pytorch-geometric.readthedocs.io/en/latest/generated/torch_geometric.nn.conv.SAGEConv.html?highlight=SageConv#torch-geometric-nn-conv-sageconv) although with [HeteroConv ](https://pytorch-geometric.readthedocs.io/en/latest/generated/torch_geometric.nn.conv.HeteroConv.html?highlight=HeteroConv#torch-geometric-nn-conv-heteroconv)that allows for edge attributes.
- [GatedGraphConv](https://pytorch-geometric.readthedocs.io/en/latest/generated/torch_geometric.nn.conv.GatedGraphConv.html?highlight=GatedGraphConv)
- [RGCNConv](https://pytorch-geometric.readthedocs.io/en/latest/generated/torch_geometric.nn.conv.RGCNConv.html?highlight=RGCNConv#torch-geometric-nn-conv-rgcnconv)

None of these allow for edge features, hence your conclusion. 
Although, some allow for edge weights (e.g. GatedGraphConv), and others for edge type (e.g. RGCNConv)
