### ISSUE TITLE
Feature request for Graph-Structure-Learning GNN for temporal Graph

### ISSUE THREAD

**Issue by seifer08ms** [benedekrozemberczki/pytorch_geometric_temporal#25]
Is there a plan to include Graph-Structure-Learning graph neural network models for temporal graphs? A few models with github repos include MTGNN(https://github.com/nnzhan/MTGNN) and Graph-WaveNet (https://github.com/nnzhan/Graph-WaveNet)

**Comment by benedekrozemberczki** [comment]
Hi there :)

Are there other papers which you would like to see?

We are happy to hear out the community.

Bests,

Benedek

**Comment by SherylHYX** [comment]
> Is there a plan to include Graph-Structure-Learning graph neural network models for temporal graphs? A few models with github repos include MTGNN(https://github.com/nnzhan/MTGNN) and Graph-WaveNet (https://github.com/nnzhan/Graph-WaveNet)

Hi Chenliang,

Yes, we plan to add some Graph-Structure-Learning graph neural network models for temporal graphs. Thanks for reaching out:D

Best,
Yixuan He

**Comment by seifer08ms** [comment]
Thanks for quick answer!   

Besides Graph-Structure-Learning models ,  it would be amazing to implement some Transformer-based graph models for temporal prediction, such as GMAN (tf:  https://github.com/zhengchuanpan/GMAN,  https://github.com/VincLee8188/GMAN-PyTorch) and STAR( https://github.com/Majiker/STAR ) .

> Hi there :)
> 
> Are there other papers which you would like to see?
> 
> We are happy to hear out the community.
> 
> Bests,
> 
> Benedek


Cool !  I can't wait it.  

> Hi Chenliang,
> 
> Yes, we plan to add some Graph-Structure-Learning graph neural network models for temporal graphs. Thanks for reaching out:D
> 
> Best,
> Yixuan He

**Comment by SherylHYX** [comment]
> [.com/nnzhan/Graph-WaveNet](https://github.com/nnzhan/Graph-WaveNet))

Hi Chenliang,

FYI I just added MTGNN. Check it out :)

Best,
Yixuan

**Comment by seifer08ms** [comment]
> > Is there a plan to include Graph-Structure-Learning graph neural network models for temporal graphs? A few models with github repos include MTGNN(https://github.com/nnzhan/MTGNN) and Graph-WaveNet (https://github.com/nnzhan/Graph-WaveNet)
> 
> Hi Chenliang,
> 
> FYI I just added MTGNN. Check it out :)
> 
> Best,
> Yixuan

Owesome！That would be a great help for my research. Thanks a lot !

Best,
Chenliang

**Comment by SherylHYX** [comment]
> Besides Graph-Structure-Learning models , it would be amazing to implement some Transformer-based graph models for temporal prediction, such as GMAN (tf: https://github.com/zhengchuanpan/GMAN, https://github.com/VincLee8188/GMAN-PyTorch) and STAR( https://github.com/Majiker/STAR ) .

Hi Chenliang,

GMAN is now ready for you. Good luck with your research!

Best,
Yixuan

**Comment by attibalazs** [comment]
Would you be able to provide an example similar to the ones you have in your docs for the chickenpox and web traffic for the MTGNN network please ? For someone who is new to all of this its a steep learning curve.

Your chickenpox and web traffic examples were a great start for me thanks for providing those.
