### ISSUE TITLE
Working Colab Notebooks

### ISSUE THREAD

**Issue by bsbodden** [benedekrozemberczki/pytorch_geometric_temporal#251]
Are there some recent Jupyter notebooks that successfully install their dependencies and properly run on Google Colab? None of the notebooks in the repo seem to work on Colab as of Oct 2023, and I've given up with a local install due to the M2 chip set being Python problematic. Any links or repos with working code would be appreciated it.

**Comment by bsbodden** [comment]
But as mentioned,   all the notebooks included in the repo are not runnable as they are.

**Comment by bsbodden** [comment]
Will try to send a PR for those

**Comment by davidshumway** [comment]
I got it working with the following:

```python
!pip install --no-index torch-scatter -f https://pytorch-geometric.com/whl/torch-2.1.0+cpu.html > /dev/null
!pip install --no-index torch-sparse -f https://pytorch-geometric.com/whl/torch-2.1.0+cpu.html > /dev/null
!pip install --no-index torch-cluster -f https://pytorch-geometric.com/whl/torch-2.1.0+cpu.html > /dev/null
!pip install --no-index torch-spline-conv -f https://pytorch-geometric.com/whl/torch-2.1.0+cpu.html > /dev/null
!pip install torch-geometric > /dev/null
!pip install geomloss[full] > /dev/null
!pip install torch-geometric-temporal
```
