### ISSUE TITLE
How to use layers which don't require time series?

### ISSUE THREAD

**Issue by sinjako** [benedekrozemberczki/pytorch_geometric_temporal#29]
Hello, i noticed that in the example given in the docs using the DCrnn with the Chickenpox dataset, we dont train over the temporal graph but on each individual snapshot instead. Indeed, many of the NN's in the docs require an input of dimension Num Nodes X Num features. But the STGCN requires an input of a time series,  so the looping over the snapshots doesnt quite work here. My question is, how do you combine these different layers?

Also: How do move the tensors in the loaders over to work on the GPU? I can use .to(device) on the model, but i can't use it on the loaders. I can use it on the snapshots individually when run through an enumerator, but that is very very slow.

**Comment by benedekrozemberczki** [comment]
Hi there @sinjako,

I do not know whether this helps:

0. The goal of the library is spatiotemporal signal processing. In that setting the features are dynamic the graph can be static. 
1. The reason for the snapshot transfer to GPU is to help potential scaling when the graph is large and you train on local receptive fields.

Bests,

Benedek

**Comment by sinjako** [comment]
I believe there has been an misunderstanding. Say i represent my data as a temporal series, of size Samples xTimesteps x Num nodes x Num features.  I can train STGCN on this input by giving each sample directly as input. For a DCRNN, i would have to give it the sample and then loop over every timestep. My question is then, how would i combine the two, so for example having an STGCN layer feeding into a DCRNN layer in my model? Do i feed forward the result of the STGCN and then loop over every snapshot to create the output of the DCRNN?.

As to the GPU, can i really only use the GPU on individual snapshots? doesn't this mean that i cant ever use GPU when training STGCN?

**Comment by benedekrozemberczki** [comment]
You can use the diagonal batching trick through time.

**Comment by sinjako** [comment]
> You can use the diagonal batching trick through time.

I tried googling that, and as of yet, i still have no idea if that is how i can combine the different neural networks or if it is how i will be able to shift the iterator object to gpu. Could you clarify?
