### ISSUE TITLE
 Evolve GCN H example

### ISSUE THREAD

**Issue by Fatima-200159617** [benedekrozemberczki/pytorch_geometric_temporal#3]
Hello,
I have a question regarding the example you provided. As per my understanding the example is showing how using EvolveGCN-H 
I am new to temporal graph neural, and what I got from EvolveGCN paper is that at each timestep the model will have a different snapshot of the graph but in the example only a static graph is given as an input to the model. Could you please advice and help on how it is exactly working?

**Comment by benedekrozemberczki** [comment]
You could use a for loop to iterate over the graphs and feed in new ones.

**Comment by Fatima-200159617** [comment]
Thanks a lot for your quick response. Could you please share any examples.

**Comment by benedekrozemberczki** [comment]
The other example in the examples folder might be helpful

**Comment by benedekrozemberczki** [comment]
I have added an example, take a look. Please star the repo if you find it useful and follow me on github.

**Comment by Fatima-200159617** [comment]
Thanks a lot that's really helpful. I just have a question, since EvolveGCN is using GRU/LSTM aren't we supposed to specify the sequence length (number of timesteps) as one of the parameters as we do when implementing any GRU/LSTM model. If that's the case what is the format of the input given that each timestep should be a different graph with new nodes or edges.
Another question I can see that the number of nodes is a parameter, by specifying this it means it is the max of nodes that graph can have right? so it can not be flexible to have more nodes?

**Comment by benedekrozemberczki** [comment]
It is a single cell, the example shown is a single cell but the graph is
randomly regenerated. One of the models has a pooling operator which
results in the lack of transfer learning. Please take a look at the
original paper.
