### ISSUE TITLE
Datasets links are broken

### ISSUE THREAD

**Issue by jmftrindade** [benedekrozemberczki/pytorch_geometric_temporal#4]
Hi there!  It looks like the links to "datasets" are broken, both on the README.md file, as well as on the docs.  Cheers --Joana

**Comment by benedekrozemberczki** [comment]
Hi there Joana,

This is still work in progress. It is just a place holder. Soon I will have a few cool datasets.

Bests,

Benedek

**Comment by benedekrozemberczki** [comment]
I will elaborate. The aim would be to have a properly tested 1.0 version of this in early 2021.
