### ISSUE TITLE
Transforming raw chickenpox dataset to json input data format

### ISSUE THREAD

**Issue by attibalazs** [benedekrozemberczki/pytorch_geometric_temporal#40]
First of all thanks for an amazing library I have been experimenting with it this week.

Would you be able to share the code for how you went from the tabular format to the json format for the Hungarian Chickenpox dataset please ?

thanks

**Comment by benedekrozemberczki** [comment]
We donated the raw dataset to the UCI ML repository.

**Comment by attibalazs** [comment]
yes I saw the raw dataset in your other repo also, thanks for that.
I was wondering if you can share the code which transforms the csv files to the json file used in the library.

**Comment by benedekrozemberczki** [comment]
I will make the loader to use the lags so you can play around.
