### ISSUE TITLE
Not all tests pass on GPU environment

### ISSUE THREAD

**Issue by attibalazs** [benedekrozemberczki/pytorch_geometric_temporal#46]
Hi all, just thought I would let you know that not all your tests pass when running on a machine with a GPU

I was looking at the MTGNN test which started working once I set the device to CPU and wasn't working with the existing code
```

   #device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    device = torch.device("cpu")
```

> 
> 
> =========================================================================== short test summary info ============================================================================
> FAILED test/convolutional_test.py::test_astgcn - RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
> FAILED test/convolutional_test.py::test_mstgcn - RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
> FAILED test/convolutional_test.py::test_gman - RuntimeError: Expected object of device type cuda but got device type cpu for argument #1 'self' in call to _thnn_conv2d_forward
> =================================================================== 3 failed, 33 passed in 67.57s (0:01:07) ====================================================================
> (pytorch_latest_p36) sh-4.2$

**Comment by benedekrozemberczki** [comment]
I will take a look into it.

**Comment by benedekrozemberczki** [comment]
Do you have some details about the line that fails and the traceback?

**Comment by SherylHYX** [comment]
Thanks for point out. I will also have a look. I wrote these tests on a CPU machine previously.

**Comment by attibalazs** [comment]
in the test_mtgnn() function in tests

Traceback:

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-6-d806b0b55523> in <module>
----> 1 test_mtgnn()

<ipython-input-5-d6f841f8aaf8> in test_mtgnn()
     29     device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
     30     edge_index = barabasi_albert_graph(num_nodes, num_edges).to(device)
---> 31     A_tilde = torch.sparse_coo_tensor(edge_index, torch.ones(edge_index.size(1)), (num_nodes, num_nodes)).to_dense()
     32     x_all = 2 * torch.rand(batch_size, seq_in_len, num_nodes, in_dim) - 1
     33     model = MTGNN(gcn_true=gcn_true, build_adj=build_adj, gcn_depth=gcn_depth, num_nodes=num_nodes,

RuntimeError: backend of indices (CUDA) must match backend of values (CPU)
```

**Comment by SherylHYX** [comment]
Yes, thanks! I am fixing it now. Give me several minutes:)

> in the test_mtgnn() function in tests
> 
> Traceback:
> 
> ```
> ---------------------------------------------------------------------------
> RuntimeError                              Traceback (most recent call last)
> <ipython-input-6-d806b0b55523> in <module>
> ----> 1 test_mtgnn()
> 
> <ipython-input-5-d6f841f8aaf8> in test_mtgnn()
>      29     device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
>      30     edge_index = barabasi_albert_graph(num_nodes, num_edges).to(device)
> ---> 31     A_tilde = torch.sparse_coo_tensor(edge_index, torch.ones(edge_index.size(1)), (num_nodes, num_nodes)).to_dense()
>      32     x_all = 2 * torch.rand(batch_size, seq_in_len, num_nodes, in_dim) - 1
>      33     model = MTGNN(gcn_true=gcn_true, build_adj=build_adj, gcn_depth=gcn_depth, num_nodes=num_nodes,
> 
> RuntimeError: backend of indices (CUDA) must match backend of values (CPU)
> ```
> 
> torch.sparse_coo_tensor also takes a device param the default is device=None so setting this to device=device but then it runs into the next error

**Comment by SherylHYX** [comment]
I fix it now. Sorry about that.

**Comment by attibalazs** [comment]
hey now worries :) thanks for putting together a great framework really enjoyed digging into it.
