### ISSUE TITLE
MTGNN example

### ISSUE THREAD

**Issue by attibalazs** [benedekrozemberczki/pytorch_geometric_temporal#48]
Do you have a good example of the MTGNN network, I like the examples you did for the chickenpox data and the web traffic I learned a lot from them. I am looking at the original implementation of MTGNN and the original paper, but would like to use MTGNN with your library also. I was looking at your unit tests for inspiration.

**Comment by benedekrozemberczki** [comment]
No, right now the primary focus is on testing and finishing the system design white paper. However, we always welcome contributions to the library and the documentation. Feel free to create a PR.

**Comment by attibalazs** [comment]
I am working backwards from your unit test on MTGNN and trying to create an example. My challenge is also to add context features. If I am successful at this will definitely raise a PR.
