### ISSUE TITLE
DCRNN source code problems

### ISSUE THREAD

**Issue by ystephenai** [benedekrozemberczki/pytorch_geometric_temporal#50]
Hi,
In the diffusion convolution layer of DCRNN, I doubt whether the message passing flow directions for Dout and Din are the same. Because in your source code, they share the same direction "source to target". But in the original paper, I think they are different since one is (Dout)-1 @ W and the other is (Din)-1 @ W **transpose**. Maybe the second term with W transpose change the flow direction,
Could you have a check on that? Maybe I am wrong.
Thanks

**Comment by benedekrozemberczki** [comment]
@paulmorio Could you take a look at this?
