### ISSUE TITLE
STGCN

### ISSUE THREAD

**Issue by ystephenai** [benedekrozemberczki/pytorch_geometric_temporal#51]
PQ = P * Q not P + Q

**Comment by benedekrozemberczki** [comment]
@paulmorio Could you take a look at this?

**Comment by paulmorio** [comment]
Sorry for the late action on this. 
Thanks for spotting this typo. It should indeed be the Hadamard product not addition. A fix will be uploaded shortly.

Will comment again when the fix is in master.
