### ISSUE TITLE
How does the temporal information flow in DCRNN example

### ISSUE THREAD

**Issue by jamestszhim** [benedekrozemberczki/pytorch_geometric_temporal#52]
I have a question about the temporal part in the DCRNN example.

In the DCRNN example: 
```python 
for time, snapshot in enumerate(train_dataset):
        y_hat = model(snapshot.x, snapshot.edge_index, snapshot.edge_attr)
        cost = cost + torch.mean((y_hat-snapshot.y)**2)
```
If I understand correctly, the snapshot in each epoch is the graph at time t (G_t), so the DCRNN model takes in G_t and predicts the target at time t. However, in temporal modelling, is it correct that the model should take in a sequence of graphs, say like (G_t, G_t-1, G_t-2, ...), and predict the target at time t? If I understand it correctly, DCRNN should maintain a stack of GRU cells capturing the inputs from different time stamps but I could not find the way to do it. 

In the current example, it seems that the model predicts on a single graph input, is it correct? Did I miss anything or I need to implement the temporal part manually?

Thanks!

**Comment by benedekrozemberczki** [comment]
1. The feature blocks are already lagged values.
2. The model keeps a memory based on the sequence seen so far.
3. Naturally, You can chain multiple GRUs together.

Could you star the repo?

**Comment by jamestszhim** [comment]
Thanks a lot, very nice repo. I starred it. Do you mind answering one more question so I make sure I understand your reply correctly? 

When you say (2) the model keeps a “memory”, I look at the code the hidden state ‘H’ seems not being saved or passed to the next time stamp automatically. I have to chain up the DCRNN cells and pass the output state ‘H’ to the next time step manually, right? Or the “memory” you are referring to is the model weights are trained from previous steps.

Thanks a lot.

**Comment by benedekrozemberczki** [comment]
Yes, you have to pass on the H to the next step.
