### ISSUE TITLE
Request for some examples to reproduce the paper

### ISSUE THREAD

**Issue by seifer08ms** [benedekrozemberczki/pytorch_geometric_temporal#53]
Is there any plan to provide a few out-of-the-box examples (such as DCRNN or others) for reproducing the  results of the original papers? I believe it would be helpful for us to check the implementation or use. Thanks!

Best,
Chenliang Wang

**Comment by benedekrozemberczki** [comment]
Hi there,

Would you like to contribute some of those?

Bests,

Benedek

**Comment by seifer08ms** [comment]
> Hi there,
> 
> Would you like to contribute some of those?
> 
> Bests,
> 
> Benedek

Yeah, I'm interested.  I'll try to help, just been a bit swamped, so it may be a while.

Best,
Chenliang Wang
