### ISSUE TITLE
Different number of time-step on METR-LA and PEMS-BAY datasets

### ISSUE THREAD

**Issue by jeongwhanchoi** [benedekrozemberczki/pytorch_geometric_temporal#60]
Both datasets are different from the dataset of the DCRNN paper.
It has a different number of time steps.

Could you explain some differences from DCRNN's dataset?

**Comment by benedekrozemberczki** [comment]
Hi there @jeongwhanchoi,

@paulmorio Could you take a look into this!

Bests,

Benedek

**Comment by jeongwhanchoi** [comment]
- PEMS-BAY Dataset
 - DCRNN official code from [DCRNN official repo](https://github.com/chnsh/DCRNN_PyTorch): 
  - timesteps=52116
 - pytorch_geometric_temporal: 
  - timesteps=52105

**Comment by benedekrozemberczki** [comment]
Did you check the number of steps you lose with lags? The number of steps
in and out part. I feel like that you are seeing that.
