### ISSUE TITLE
2D weight for DCRNN

### ISSUE THREAD

**Issue by geoHeil** [benedekrozemberczki/pytorch_geometric_temporal#63]
How can I pass a multidimensional weight to a DCRNN?

Using the example RGCN:

```
class RecurrentGCN(torch.nn.Module):
    def __init__(self, node_features):
        super(RecurrentGCN, self).__init__()
        self.recurrent = DCRNN(node_features, 32, 1)
        self.linear = torch.nn.Linear(32, 1)
    def forward(self, x, edge_index, edge_weight):
        h = self.recurrent(x, edge_index, edge_weight) # fails if edge_weight is of 2D shape (2/#n_examples)
        #h = self.recurrent(x, edge_index) # works (= no weights used)
        h = F.relu(h)
        h = self.linear(h)
        return h 
```

I get
```
RuntimeError: The expanded size of the tensor (2) must match the existing size (4871) at non-singleton dimension 0.  Target sizes: [2, 4871].  Tensor sizes: [4871, 1]
```

when a 2D weight vector is passed.

Why is only a 1D weight vector accepted? What would need to be changed to support multidimensional weights?

**Comment by benedekrozemberczki** [comment]
Because, the original paper is not designed to do that. It is an
implementation of what is done in the paper and not an implementation of
what should be tone. You could parameterize the edge weights like we did in
this paper:

https://github.com/benedekrozemberczki/PDN

**Comment by geoHeil** [comment]
However, as the number of edges is not constant (=dynamic) any reshape operation to apply the suggested fixup is potentially going to fail.

Can you @benedekrozemberczki recommend any of the implemented layers where multidimensional weights would work or explain how to adapt the fixup to a dynamic graph with a changing number of edges?

**Comment by geoHeil** [comment]
Using https://github.com/benedekrozemberczki/pytorch_geometric_temporal/blob/master/torch_geometric_temporal/nn/recurrent/attentiontemporalgcn.py#L5 

and changing one line from:

```
self.recurrent = DCRNN(node_features, 32, 8)
```

to:

```
self.recurrent = A3TGCN(8, 32, node_features)
```

I can now support multidimensional temporal node features.

However, for not yet for the edge features.
