### ISSUE TITLE
Example code

### ISSUE THREAD

**Issue by CongWeilin** [benedekrozemberczki/pytorch_geometric_temporal#67]
Hi, I found this repository is very helpful for future research on dynamic graphs. I wonder if you can also release the code you used to generate Table 4 in the [white paper](https://arxiv.org/abs/2104.07788)?

Besides, I am not sure if you are planning (1) to compare the performance of the code in this repository to their original code? and  (2) supporting more datasets that were used in the existing works?

**Comment by benedekrozemberczki** [comment]
Hi there, we will release more examples for sure. We are going to add existing datasets, PemsBay and MetrLA are already integrated.

**Comment by benedekrozemberczki** [comment]
Is there anything you want to see?

**Comment by CongWeilin** [comment]
Hi, I think adding dataset such as BC-OTC, BC-Alpha, AS, Reddit, Elliptic used in [EvolveGCN](https://arxiv.org/pdf/1902.10191.pdf), Enron, UCI, Yelp, ML-10M in [DySAT](https://dl.acm.org/doi/pdf/10.1145/3336191.3371845), and PeMSD4, PeMSD8 in [AGCRN](https://arxiv.org/pdf/2007.02842.pdf) would be extremely helpful.

I feel like one of the biggest issues in dynamic graph research comparing to static graph research is its reproducibility and pair comparison. And I believe this repository can help fix this issue.  

If you can provide some examples (e.g., the code used to generate that Table 4), I would also love to contribute.

**Comment by benedekrozemberczki** [comment]
Yes, I totally agree that there are major issues within this specific domain of ML. We will add some additional examples later on so you can play around. The AGCRN model has a bug which we are investigating right now Gradients evaluate for NaN.
