### ISSUE TITLE
Question about the demo code：Web Traffic Prediction

### ISSUE THREAD

**Issue by dgh19940** [benedekrozemberczki/pytorch_geometric_temporal#69]
The input of each step in GRU contains the edge features of the current time step and the hidden state of the previous step. In the official demo “Web Traffic Prediction”，it seems that the hidden state of the previous time step is not entered at each time. So is it set in the relevant GConvGRU layer？

**Comment by benedekrozemberczki** [comment]
It is a simple demo example. You can use a design where you are passing around the states.

**Comment by dgh19940** [comment]
> It is a simple demo example. You can use a design where you are passing around the states.
Thank you~
