### ISSUE TITLE
Example of how to pass a sequence of graphs

### ISSUE THREAD

**Issue by semirelezovikj** [benedekrozemberczki/pytorch_geometric_temporal#70]
How would one go about passing a sequence of graphs (possibly variable length sequences) into any of the methods? 

Let's take for example LRGCN: designed to deal with a sequence of graph snapshots. Let's say I have 30 sequences of max_length 5 (minimum 1 graph, maximum 5 graphs or 5 timesteps). Any examples on how to accomplish this? 

Pytorch has `padding` and `packing` methods to deal with variable length sequences.

**Comment by benedekrozemberczki** [comment]
You can pass in empty snapshots.

**Comment by semirelezovikj** [comment]
@benedekrozemberczki Do you have a way of passing an entire sequence, or do I have to pass each snapshot in a for-loop?

Thanks for your reply
