### ISSUE TITLE
[Feature Request] Make PyTorch Geometric available via Anaconda (conda-forge channel)

### ISSUE THREAD

**Issue by MoRoBe-Work** [benedekrozemberczki/pytorch_geometric_temporal#76]
Hi,
First of all thanks for providing this package which provides an extremely convenient way of testing different approaches from literature on you own data. Now, about my request: PyTorch Geometric is available through conda, thus it would be very comfortable to have PyTorch Geometric Temporal available there as well. Do you have any plans of adding a conda recipe? I understand that this is merely a convenience feature as running PyTorch Geometric Temporal in a virtual environment via virtualenv is absolutely viable, however it would add it nicely into a simple data science environment.
Best Regards
MoRoBe

**Comment by benedekrozemberczki** [comment]
Hi there,

Do you want to contribute this?

Bests,

Benedek

**Comment by MoRoBe-Work** [comment]
Hey,
Unfortunately I have never done so before. I could try nonetheless but will have to see when I can do the necessary reading. Please leave this issue open for now, I'll definitely get back to you once I sorted out some more urgent tasks.
Best,
MoRoBe

**Comment by MoRoBe-Work** [comment]
Hi, 
I was able to generate a basically complete recipe but the tests fail with

`OSError: /home/conda/staged-recipes/build_artifacts/torch-geometric-temporal_1623933364794/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.8/site-packages/torch_sparse/_version.so: undefined symbol: _ZN3c1017RegisterOperatorsC1Ev`

According to rusty1s/pytorch_geometric#1657 this happens when "when external libraries are compiled with a different PyTorch version than the one you are using". The solution there is to build the other packages from source as well which is not a proper solution here. If you'd like to support me in fixing this I'd be very grateful. There is a corresponding PR (suggested by the conda-forge chatroom on https://gitter.im/conda-forge/conda-forge.github.io for problem solving) to be found under:

https://github.com/conda-forge/staged-recipes/pull/15329

So any discussion would best fit there. 
Also, I only entered myself as a maintainer, assuming you don't want to troubleshoot conda-specific problems. Of course you are the person to decide whose listed there! 

Best regards
MoRoBe

**Comment by MoRoBe-Work** [comment]
As stated in the PR mentioned above there is an underlying problem with the conda recipes for PyTorch Geometric. Therefor I no longer pursue this. A Pipfile for an installation of the current version can be found there as well.

**Comment by benedekrozemberczki** [comment]
PyTorch Geometric became available on conda!

**Comment by MoRoBe-Work** [comment]
It is available on conda-forge, but the current recipe does not work, or at least I wasn't able to get it to work. If you think I missed something please read the discussion in the [PR](https://github.com/conda-forge/staged-recipes/pull/15329) to add the PyTorch Geometric Temporal recipe. I have little understanding of the underlying problem and after spending two work days rather used pipenv. I'd still be happy to help with publishing PyTorch Geometric Temporal on conda-forge, I just don't see how (with reasonable effort) at the moment.
