### ISSUE TITLE
Feature request for non-recurrent GNN models

### ISSUE THREAD

**Issue by aravindsankar28** [benedekrozemberczki/pytorch_geometric_temporal#8]
Is there a plan to include self-attentional and memory-based graph neural network models for temporal graphs? A few models with github repos include DySAT (https://github.com/aravindsankar28/DySAT) and TGN (https://github.com/twitter-research/tgn)

**Comment by benedekrozemberczki** [comment]
Dear Aravind,

The library will be focusing on models that can deal with the following types of settings.

1. Discrete time - static graph.
2. Discrete time - dynamic graph.
3. Continuous time - static graph.
4. Continuous time - dynamic graph.
 
The current data iterator, splitter and toy dataset is suitable for the first setting. Models included can deal with the first and second setting. If you want to contribute feel free to open a PR. We will write a paper out of the library and submit to a reasonable venue. Everyone who makes a meaningful contribution will get their name on the paper as a co-author.

Bests,

Benedek
