### ISSUE TITLE
[Bug?] the way to set GCN.weight in EvolveGCN.

### ISSUE THREAD

**Issue by maqy1995** [benedekrozemberczki/pytorch_geometric_temporal#80]
Hi @benedekrozemberczki,
    I found that the gradient function may be lost in the implementation of EvolveGCN. The reason for this should be the following line of code: https://github.com/benedekrozemberczki/pytorch_geometric_temporal/blob/bd6fac946378507a729b5723e9ace46a9dc0cbe1/torch_geometric_temporal/nn/recurrent/evolvegcno.py#L69
    And here is a demo try to verify it:
``` python
import torch

torch.manual_seed(123)


class MyModel(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.toy_model = ToyModel(weight=True)

    def forward(self, x):
        W = self.toy_model.weight
        self.toy_model.weight = torch.nn.parameter.Parameter(W)
        return self.toy_model(x)


class MyModelParam(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.W = torch.nn.parameter.Parameter(torch.Tensor(2, 3).fill_(0.5))
        self.toy_model = ToyModel(weight=False)

    def forward(self, x):
        W = self.W
        return self.toy_model(x, weight=W)


class ToyModel(torch.nn.Module):
    def __init__(self, weight=True):
        super().__init__()
        if weight:
            self.weight = torch.nn.parameter.Parameter(torch.Tensor(2, 3).fill_(0.5))
        else:
            self.register_parameter('weight', None)
        # self.func = torch.nn.parameter.Parameter(torch.Tensor(2, 2).fill_(0.1))

    def forward(self, x, weight=None):
        if weight is not None:
            w = weight
        else:
            w = self.weight
        # x = self.func * x
        x = torch.matmul(x, w)
        return x


x = torch.Tensor(1, 2).fill_(0.8)
y = torch.Tensor(1, 3).fill_(0.7)
print("################## Test 1: reset GCN.weight by nn.Parameter()##################")
model = MyModel()
print("toyModel weight before:")
print(model.toy_model.weight)
optim = torch.optim.SGD(model.parameters(), lr=1e-2)

# print("x: {}".format(x))
# print("y: {}".format(y))
prediction = model(x)
loss = (prediction - y).sum()
loss.backward()
optim.step()
print("toyModel weight after:")
print(model.toy_model.weight)

########################## Test 2
print("################## Test 2: pass weight as a parameter during forward##################")
model_param = MyModelParam()
print("model param weight before:")
print(model_param.W)
optim_param = torch.optim.SGD(model_param.parameters(), lr=1e-2)
x_param = torch.Tensor(1, 2).fill_(0.8)
y_param = torch.Tensor(1, 3).fill_(0.7)
# print("x_param: {}".format(x_param))
# print("y_param: {}".format(y_param))
prediction_param = model_param(x_param)
loss_param = (prediction_param - y_param).sum()
loss_param.backward()
optim_param.step()
print("model param weight after:")
print(model_param.W)
```
result is here:
```
################## Test 1: reset GCN.weight by nn.Parameter()##################
toyModel weight before:
Parameter containing:
tensor([[0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000]], requires_grad=True)
toyModel weight after:
Parameter containing:
tensor([[0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000]], requires_grad=True)
################## Test 2: pass weight as a parameter during forward##################
model param weight before:
Parameter containing:
tensor([[0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000]], requires_grad=True)
model param weight after:
Parameter containing:
tensor([[0.4920, 0.4920, 0.4920],
        [0.4920, 0.4920, 0.4920]], requires_grad=True)

Process finished with exit code 0
```
We can see that if we set `model.weight` in each batch iter by `nn.paramter.Parameter()`, the weight has not been updated.  
One way to fix it should be to pass a new `weight` during every forward. But pyG does not seem to provide the corresponding interface.

**Comment by benedekrozemberczki** [comment]
This sounds problematic, let me think about this - I will ask Matthias Fey about this one.

**Comment by maqy1995** [comment]
Hi @benedekrozemberczki, are there any updates?

**Comment by icecity96** [comment]
Another problem is the GCN.weight in EvolveGCN should set the `requires_grad` to `False`. Since this weight is not trainable.

**Comment by maqy1995** [comment]
Hi @icecity96, thanks for your reply.  
From the official code, the weight of GCN seems not set `requires_grad` to `False`, which means it should be trainable, see here:
https://github.com/IBM/EvolveGCN/blob/90869062bbc98d56935e3d92e1d9b1b4c25be593/egcn_o.py#L56

To the second problem:
`self.toy_model.weight.data = torch.nn.parameter.Parameter(W)` is work in this toy demo, but not work in `EvolveGCN`.  We can add a function to 'W'(simulate the role of RNN), and we can see the result is different.
```
import torch
torch.manual_seed(123)


class MyModel(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.toy_model = ToyModel(weight=True)

    def forward(self, x):
        W = self.toy_model.weight
        W = torch.tan(W)  # add a function to W
        self.toy_model.weight.data = torch.nn.parameter.Parameter(W)
        return self.toy_model(x)


class MyModelParam(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.W = torch.nn.parameter.Parameter(torch.Tensor(2, 3).fill_(0.5))
        self.toy_model = ToyModel(weight=False)

    def forward(self, x):
        W = self.W
        W = torch.tan(W)
        return self.toy_model(x, weight=W)


class ToyModel(torch.nn.Module):
    def __init__(self, weight=True):
        super().__init__()
        if weight:
            self.weight = torch.nn.parameter.Parameter(torch.Tensor(2, 3).fill_(0.5))
        else:
            self.register_parameter('weight', None)
        # self.func = torch.nn.parameter.Parameter(torch.Tensor(2, 2).fill_(0.1))

    def forward(self, x, weight=None):
        if weight is not None:
            w = weight
        else:
            w = self.weight
        # x = self.func * x
        x = torch.matmul(x, w)
        return x


x = torch.Tensor(1, 2).fill_(0.8)
y = torch.Tensor(1, 3).fill_(0.7)
print("################## Test 1: reset GCN.weight by nn.Parameter()##################")
model = MyModel()
print("toyModel weight before:")
print(model.toy_model.weight)
optim = torch.optim.SGD(model.parameters(), lr=1e-2)

# print("x: {}".format(x))
# print("y: {}".format(y))
prediction = model(x)
loss = (prediction - y).sum()
loss.backward()
optim.step()
print("toyModel weight after:")
print(model.toy_model.weight)

########################## Test 2
print("################## Test 2: pass weight as a parameter during forward##################")
model_param = MyModelParam()
print("model param weight before:")
print(model_param.W)
optim_param = torch.optim.SGD(model_param.parameters(), lr=1e-2)
x_param = torch.Tensor(1, 2).fill_(0.8)
y_param = torch.Tensor(1, 3).fill_(0.7)
# print("x_param: {}".format(x_param))
# print("y_param: {}".format(y_param))
prediction_param = model_param(x_param)
loss_param = (prediction_param - y_param).sum()
loss_param.backward()
optim_param.step()
print("model param weight after:")
print(model_param.W)
```

result is here:
```
################## Test 1: reset GCN.weight by nn.Parameter()##################
toyModel weight before:
Parameter containing:
tensor([[0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000]], requires_grad=True)
toyModel weight after:
Parameter containing:
tensor([[0.5383, 0.5383, 0.5383],
        [0.5383, 0.5383, 0.5383]], requires_grad=True)
################## Test 2: pass weight as a parameter during forward##################
model param weight before:
Parameter containing:
tensor([[0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000]], requires_grad=True)
model param weight after:
Parameter containing:
tensor([[0.4896, 0.4896, 0.4896],
        [0.4896, 0.4896, 0.4896]], requires_grad=True)
```

**Comment by SherylHYX** [comment]
From https://github.com/IBM/EvolveGCN/blob/90869062bbc98d56935e3d92e1d9b1b4c25be593/egcn_o.py#L77 I guess https://github.com/benedekrozemberczki/pytorch_geometric_temporal/blob/439d9af14bf3303835296258fa415aea1d6c782e/torch_geometric_temporal/nn/recurrent/evolvegcno.py#L47 should even be GRU instead of LSTM, but as input we have ```_, W = self.recurrent_layer(W,W)``` but this still cannot solve the problem of not updating the weights.

**Comment by SherylHYX** [comment]
The problem could be that the weights of recurrent layer are not updated. I will have a closer look later.

**Comment by SherylHYX** [comment]
I tested the mat_GRU_cell class from the original implementation as our recurrent_layer, which would work. The problem might be related to the use of the single-layer LSTM/GRU. The original implementation writes out the GRU functionality explicitly while here we use GRU from torch. Treating the length as one might be problematic.

**Comment by SherylHYX** [comment]
Another difference is that the bias in the original implementation is a matrix while in GRU/LSTM bias is a vector. Therefore, for the example given, the number of recurrent parameters inside the EvolveGCNO class is 4*4*9=144 for the original implementation while that is 12*10=120 for GRU and 16*10=160 for LSTM.

**Comment by SherylHYX** [comment]
> Hi @icecity96, thanks for your reply.
> From the official code, the weight of GCN seems not set `requires_grad` to `False`, which means it should be trainable, see here:
> https://github.com/IBM/EvolveGCN/blob/90869062bbc98d56935e3d92e1d9b1b4c25be593/egcn_o.py#L56
> 
> To the second problem:
> `self.toy_model.weight.data = torch.nn.parameter.Parameter(W)` is work in this toy demo, but not work in `EvolveGCN`. We can add a function to 'W'(simulate the role of RNN), and we can see the result is different.
> 
> ```python
> import torch
> torch.manual_seed(123)
> 
> 
> class MyModel(torch.nn.Module):
>     def __init__(self):
>         super().__init__()
>         self.toy_model = ToyModel(weight=True)
> 
>     def forward(self, x):
>         W = self.toy_model.weight
>         W = torch.tan(W)  # add a function to W
>         self.toy_model.weight.data = torch.nn.parameter.Parameter(W)
>         return self.toy_model(x)
> 
> 
> class MyModelParam(torch.nn.Module):
>     def __init__(self):
>         super().__init__()
>         self.W = torch.nn.parameter.Parameter(torch.Tensor(2, 3).fill_(0.5))
>         self.toy_model = ToyModel(weight=False)
> 
>     def forward(self, x):
>         W = self.W
>         W = torch.tan(W)
>         return self.toy_model(x, weight=W)
> ```
> 
> result is here:
> 
> ```
> ################## Test 1: reset GCN.weight by nn.Parameter()##################
> toyModel weight before:
> Parameter containing:
> tensor([[0.5000, 0.5000, 0.5000],
>         [0.5000, 0.5000, 0.5000]], requires_grad=True)
> toyModel weight after:
> Parameter containing:
> tensor([[0.5383, 0.5383, 0.5383],
>         [0.5383, 0.5383, 0.5383]], requires_grad=True)
> ################## Test 2: pass weight as a parameter during forward##################
> model param weight before:
> Parameter containing:
> tensor([[0.5000, 0.5000, 0.5000],
>         [0.5000, 0.5000, 0.5000]], requires_grad=True)
> model param weight after:
> Parameter containing:
> tensor([[0.4896, 0.4896, 0.4896],
>         [0.4896, 0.4896, 0.4896]], requires_grad=True)
> ```
The difference is due to tangent: @maqy1995 . If you do the following, you would obtain the same result:
```
x = torch.Tensor(1, 2).fill_(0.8)
y = torch.Tensor(1, 3).fill_(0.7)
print("################## Test 1: reset GCN.weight by nn.Parameter()##################")
model = MyModel()
print("toyModel weight before:")
print(model.toy_model.weight)
optim = torch.optim.SGD(model.parameters(), lr=1e-2)

# print("x: {}".format(x))
# print("y: {}".format(y))
prediction = model(x)
loss = (prediction - y).sum()
loss.backward()
print("toyModel weight gradient:")
print(model.toy_model.weight.grad)
optim.step()
print("toyModel weight after:")
print(model.toy_model.weight)
print("model param weight after:")
print(torch.tan(model.toy_model.weight))


########################## Test 2
print("################## Test 2: pass weight as a parameter during forward##################")
model_param = MyModelParam()
print("model param weight before:")
print(model_param.W)
optim_param = torch.optim.SGD(model_param.parameters(), lr=1e-2)
x_param = torch.Tensor(1, 2).fill_(0.8)
y_param = torch.Tensor(1, 3).fill_(0.7)
# print("x_param: {}".format(x_param))
# print("y_param: {}".format(y_param))

prediction_param = model_param(x_param)
loss_param = (prediction_param - y_param).sum()
loss_param.backward()
print("model param weight gradient:")
print(model_param.W.grad)
optim_param.step()
print("model param weight after:")
print(model_param.W)
print("toyModel weight after:")
print(model.toy_model.weight)
```
Result:
```
################## Test 1: reset GCN.weight by nn.Parameter()##################
toyModel weight before:
Parameter containing:
tensor([[0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000]], requires_grad=True)
toyModel weight gradient:
tensor([[0.8000, 0.8000, 0.8000],
        [0.8000, 0.8000, 0.8000]])
toyModel weight after:
Parameter containing:
tensor([[0.5383, 0.5383, 0.5383],
        [0.5383, 0.5383, 0.5383]], requires_grad=True)
model param weight after:
tensor([[0.4938, 0.4938, 0.4938],
        [0.4938, 0.4938, 0.4938]], grad_fn=<AtanBackward>)
################## Test 2: pass weight as a parameter during forward##################
model param weight before:
Parameter containing:
tensor([[0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000]], requires_grad=True)
model param weight gradient:
tensor([[1.0388, 1.0388, 1.0388],
        [1.0388, 1.0388, 1.0388]])
model param weight after:
Parameter containing:
tensor([[0.4896, 0.4896, 0.4896],
        [0.4896, 0.4896, 0.4896]], requires_grad=True)
toyModel weight after:
Parameter containing:
tensor([[0.5383, 0.5383, 0.5383],
        [0.5383, 0.5383, 0.5383]], requires_grad=True)
```

**Comment by SherylHYX** [comment]
> Hi @icecity96, thanks for your reply.
> From the official code, the weight of GCN seems not set `requires_grad` to `False`, which means it should be trainable, see here:
> https://github.com/IBM/EvolveGCN/blob/90869062bbc98d56935e3d92e1d9b1b4c25be593/egcn_o.py#L56
> 
> To the second problem:
> `self.toy_model.weight.data = torch.nn.parameter.Parameter(W)` is work in this toy demo, but not work in `EvolveGCN`. We can add a function to 'W'(simulate the role of RNN), and we can see the result is different.
> 
> ```python
> import torch
> torch.manual_seed(123)
> 
> 
> class MyModel(torch.nn.Module):
>     def __init__(self):
>         super().__init__()
>         self.toy_model = ToyModel(weight=True)
> 
>     def forward(self, x):
>         W = self.toy_model.weight
>         W = torch.tan(W)  # add a function to W
>         self.toy_model.weight.data = torch.nn.parameter.Parameter(W)
>         return self.toy_model(x)
> 
> 
> class MyModelParam(torch.nn.Module):
>     def __init__(self):
>         super().__init__()
>         self.W = torch.nn.parameter.Parameter(torch.Tensor(2, 3).fill_(0.5))
>         self.toy_model = ToyModel(weight=False)
> 
>     def forward(self, x):
>         W = self.W
>         W = torch.tan(W)
>         return self.toy_model(x, weight=W)
> ```
> 
> result is here:
> 
> ```
> ################## Test 1: reset GCN.weight by nn.Parameter()##################
> toyModel weight before:
> Parameter containing:
> tensor([[0.5000, 0.5000, 0.5000],
>         [0.5000, 0.5000, 0.5000]], requires_grad=True)
> toyModel weight after:
> Parameter containing:
> tensor([[0.5383, 0.5383, 0.5383],
>         [0.5383, 0.5383, 0.5383]], requires_grad=True)
> ################## Test 2: pass weight as a parameter during forward##################
> model param weight before:
> Parameter containing:
> tensor([[0.5000, 0.5000, 0.5000],
>         [0.5000, 0.5000, 0.5000]], requires_grad=True)
> model param weight after:
> Parameter containing:
> tensor([[0.4896, 0.4896, 0.4896],
>         [0.4896, 0.4896, 0.4896]], requires_grad=True)
> ```
The difference is due to tangent: @maqy1995 . If you do the following, you would obtain the same result:
```
x = torch.Tensor(1, 2).fill_(0.8)
y = torch.Tensor(1, 3).fill_(0.7)
print("################## Test 1: reset GCN.weight by nn.Parameter()##################")
model = MyModel()
print("toyModel weight before:")
print(model.toy_model.weight)
optim = torch.optim.SGD(model.parameters(), lr=1e-2)

# print("x: {}".format(x))
# print("y: {}".format(y))
prediction = model(x)
loss = (prediction - y).sum()
loss.backward()
print("toyModel weight gradient:")
print(model.toy_model.weight.grad)
optim.step()
print("toyModel weight after:")
print(model.toy_model.weight)
print("model param weight after:")
print(torch.tan(model.toy_model.weight))


########################## Test 2
print("################## Test 2: pass weight as a parameter during forward##################")
model_param = MyModelParam()
print("model param weight before:")
print(model_param.W)
optim_param = torch.optim.SGD(model_param.parameters(), lr=1e-2)
x_param = torch.Tensor(1, 2).fill_(0.8)
y_param = torch.Tensor(1, 3).fill_(0.7)
# print("x_param: {}".format(x_param))
# print("y_param: {}".format(y_param))

prediction_param = model_param(x_param)
loss_param = (prediction_param - y_param).sum()
loss_param.backward()
print("model param weight gradient:")
print(model_param.W.grad)
optim_param.step()
print("model param weight after:")
print(model_param.W)
print("toyModel weight after:")
print(model.toy_model.weight)
```
Result:
```
################## Test 1: reset GCN.weight by nn.Parameter()##################
toyModel weight before:
Parameter containing:
tensor([[0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000]], requires_grad=True)
toyModel weight gradient:
tensor([[0.8000, 0.8000, 0.8000],
        [0.8000, 0.8000, 0.8000]])
toyModel weight after:
Parameter containing:
tensor([[0.5383, 0.5383, 0.5383],
        [0.5383, 0.5383, 0.5383]], requires_grad=True)
model param weight after:
tensor([[0.4938, 0.4938, 0.4938],
        [0.4938, 0.4938, 0.4938]], grad_fn=<AtanBackward>)
################## Test 2: pass weight as a parameter during forward##################
model param weight before:
Parameter containing:
tensor([[0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000]], requires_grad=True)
model param weight gradient:
tensor([[1.0388, 1.0388, 1.0388],
        [1.0388, 1.0388, 1.0388]])
model param weight after:
Parameter containing:
tensor([[0.4896, 0.4896, 0.4896],
        [0.4896, 0.4896, 0.4896]], requires_grad=True)
toyModel weight after:
Parameter containing:
tensor([[0.5383, 0.5383, 0.5383],
        [0.5383, 0.5383, 0.5383]], requires_grad=True)
```

**Comment by SherylHYX** [comment]
> Another problem is the GCN.weight in EvolveGCN should set the `requires_grad` to `False`. Since this weight is not trainable.

Yes, I agree that the weight should be updated by GRU/LSTM instead of GCN unless GCN has bias. However, unfortunately, doing this would not solve the problem of losing the gradient of GRU/LSTM.

**Comment by SherylHYX** [comment]
The reason why the gradient is lost is perhaps that the weights in the recurrent layer GRU/LSTM are viewed as intermediate nodes in the computation graph. See https://stackoverflow.com/questions/58421637/pytorch-gradients-not-calculated-for-parameters. Here is an issue related https://github.com/pytorch/pytorch/issues/31185.
