### ISSUE TITLE
How to process METR-LA and PEMS Bay datasets?

### ISSUE THREAD

**Issue by JiapengWu** [benedekrozemberczki/pytorch_geometric_temporal#82]
The feature field of METRLADatasetLoader and PemsBayDatasetLoader has 3 dimensions, while other data loaders like ChickenpoxDatasetLoader only have two. How to process batched input for the models in this case?
When I use DCRNN as encoder, I got the following error: "Tensors must have same number of dimensions: got 3 and 2."

**Comment by benedekrozemberczki** [comment]
You can iterate over the none vertex, feature dimension. You can also reshape. Please print the shape of the feature blocks and you will understand.

**Comment by JiapengWu** [comment]
OK, the input has dimension [207, 2, 12]. Supposed I have two output vectors of dimensions [207, 32], how do I combine them to get them? I don't see a proper description of this step in the original paper either...

**Comment by alexriedel1** [comment]
Each of the 207 nodes has two features and each datapoint has 12 timesteps, that's how you get the input dimensions. How would you get the [207, 32] output vector?

**Comment by JiapengWu** [comment]
@alexriedel1 As Benedek mentioned, I can iterate over the feature dimensions and get a 32d embedding for each node, this is [207,32], and I will get two of them (because there are two features). The question is how do you combine them into a single vector for forecasting?

**Comment by alexriedel1** [comment]
You could add them our you could average them, thats just two possibilities

**Comment by JiapengWu** [comment]
OK thank you, I’ll look into it.

On Jul 14, 2021, at 11:58 AM, Alexander Riedel ***@***.******@***.***>> wrote:



You could add them our you could average them, thats just two possibilities
