### ISSUE TITLE
Modulo value for one hot encoding is hardcoded, should be derived

### ISSUE THREAD

**Issue by MoRoBe-Work** [benedekrozemberczki/pytorch_geometric_temporal#85]
Hello,
In the referenced line, the "frequency", i.e. the number of timesteps per day is hardcoded. This is fine as long as steps of exactly 5 minutes are used, but is erroneous otherwise. I believe 'T', the actual number of timesteps should be used. Could you adjust that in a future version or should I open a PR? Can do, but feels kind of overkill for changing a single numeral.

The line in question:

https://github.com/benedekrozemberczki/pytorch_geometric_temporal/blob/a45aa6e96081789058e751a450928a440e8476b2/torch_geometric_temporal/nn/attention/gman.py#L140

Best regards,
MoRoBe

**Comment by benedekrozemberczki** [comment]
@SherylHYX Do you want to fix this?

**Comment by SherylHYX** [comment]
No problem! Thanks for point this out!

**Comment by MoRoBe-Work** [comment]
Of course, thank you for providing this library. Please let me know once the fix made it into the wheel, we've overwritten the function for now.
Best
MoRoBe
