### ISSUE TITLE
Question about example code

### ISSUE THREAD

**Issue by smatovski** [benedekrozemberczki/pytorch_geometric_temporal#87]
Hi,
I've been trying to reuse the example code, MPNNLSTM, GCLSTM, and GConvLSTM with my own dataset. My MSE errors are around .2 but the models do not return correct target values. When I run the examples the MSE is around 1. What does MSE represent? How should I structure data my data for these models? 
I have a graph with 20 nodes, 2 features per node, and 32 edges. The dataset has 360 separate graphs. My dataset looks similar to the one used in MPNNLSTM.

**Comment by benedekrozemberczki** [comment]
Hi there,

What are we talking about? Which dataset?

MSE is mean squared error.

https://en.wikipedia.org/wiki/Mean_squared_error

The documentation described the data types needed for loading datasets. If you are willing to contribute the dataset  we can create an integrated loader. Bests,

Benedek

**Comment by smatovski** [comment]
If I run the mpnnlstm_example.py. I get an MSE of 1.0663 using the Chickenpox dataset.
gconvlstm_example.py gives an MSE of 1.0904 with the Chickenpox dataset.
gclstm_example.py gives an MSE of  1.0784 with the Chickenpox dataset.
These MSE all look to be really high not sure if there is something wrong in the code or my environment. 

If I replace the Chickenpox dataset with one I built. The MSE drops to .2 for each model but when I look at the target data, y_hat, I am not seeing the values I am expecting. 
Not sure what I am doing wrong.

**Comment by benedekrozemberczki** [comment]
Why would the performance be the same on two different datasets?

**Comment by smatovski** [comment]
Attached is my dataset SC_Graph_synthetic.xlsx. the edge index is 
np.array([[0,5],[1,14],[1,15],[2,6],[2,9],[3,5],[3,9],[4,7],[4,15],[4,9],[5,10],[5,8],[6,8],[7,12],[7,11],[8,12],[9,19],[10,16],
                                 [10,12],[11,12],[11,13],[11,19],[12,18],[12,17],[12,16],[13,18],[13,17],[14,5],[14,6],[14,7],[15,6],[15,7]]).T
The graph is static. Also attached is a loader I created. SC_DataLoader.txt 
[SC_Graph_synthetic.xlsx](https://github.com/benedekrozemberczki/pytorch_geometric_temporal/files/6919722/SC_Graph_synthetic.xlsx)
[SC_DataLoader.txt](https://github.com/benedekrozemberczki/pytorch_geometric_temporal/files/6919728/SC_DataLoader.txt)

**Comment by smatovski** [comment]
I'm not sure why the code examples from the repo have a similar MSE. I did not modify them only ran the code on my local environment/machine. Using Acondana for my python environment.

**Comment by smatovski** [comment]
I copied the code from the Epidemiological Forecasting, https://pytorch-geometric-temporal.readthedocs.io/en/latest/notes/introduction.html#epidemiological-forecasting, and ran it. I receive an MSE of 1.0232, not 0.6866. Can you please explain why?

**Comment by benedekrozemberczki** [comment]
Different datasets have a different loss value.

**Comment by smatovski** [comment]
But if I copy the code from GitHub shouldn't I get similar results? Your example on Epidemiological Forecasting shows an MSE of .6866. I run the exact same code and got an MSE of 1.0232.

**Comment by benedekrozemberczki** [comment]
That is fine, the read the docs should be updated.

**Comment by smatovski** [comment]
Doesn't an MSE of 1.0232 mean the model is not predicting values correctly?

**Comment by benedekrozemberczki** [comment]
It means that out of sample it is roughly random - it can be distribution
shift, seasonality, and trends.

**Comment by smatovski** [comment]
Ok, so the example code evaluate the dataset and comes back with the conclusion that the dataset is very random. Meaning my dataset, SC_Graph_synthetic, is not very random. 
I want to understand how I can get one of the models to predict the target values. Do I need more data, a different model, ...

**Comment by benedekrozemberczki** [comment]
Yes, that is something that you have to experiment with.

**Comment by benedekrozemberczki** [comment]
@smatovski Could you star the repo?

**Comment by smatovski** [comment]
Started a repo of my code and dataset. https://github.com/smatovski/GNN_Supply_Chain (currently private)
