### ISSUE TITLE
Documentation: class A3TGCN, wrong paper link

### ISSUE THREAD

**Issue by AnibalGeoSpock** [benedekrozemberczki/pytorch_geometric_temporal#88]
In the repo

`A3T-GCN from Zhu et al.: A3T-GCN: Attention Temporal Graph Convolutional Network for Traffic Forecasting` linking to [https://arxiv.org/abs/2006.11583](https://arxiv.org/abs/2006.11583).

In the documentation the class A3TGCN, the description states:
`An implementation of the Temporal Graph Convolutional Gated Recurrent Cell. For details see this paper: “T-GCN: A Temporal Graph ConvolutionalNetwork for Traffic Prediction.”`
linking to: [https://arxiv.org/abs/1811.05320](https://arxiv.org/abs/1811.05320)

and it should read:
`An implementation of the Attention Temporal Graph Convolutional Network for Traffic Forecasting. For details see this paper: “Attention Temporal Graph Convolutional Network for Traffic Forecasting.”`
linking to:  [https://arxiv.org/abs/2006.11583](https://arxiv.org/abs/2006.11583).

**Comment by benedekrozemberczki** [comment]
Precisely t should read as:

and it should read:
An implementation of the Attention Temporal Graph Convolutional Network for Traffic Forecasting. For details see this paper: “A3T-GCN: Attention Temporal Graph Convolutional Network for Traffic Forecasting.”
linking to: https://arxiv.org/abs/2006.11583.
