### ISSUE TITLE
[Question] Is there a standard way, example to use my own dataset?

### ISSUE THREAD

**Issue by mkrech** [benedekrozemberczki/pytorch_geometric_temporal#91]
Hi all,
I want to do some traffic forecast and have a dataset.

Is there a standard way or example to use my own dataset?

kindly regards

**Comment by paulamartingonzalez** [comment]
There are [docs in the website](https://pytorch-geometric.readthedocs.io/en/latest/notes/create_dataset.html). I did this recently and used [this video ](https://www.youtube.com/watch?v=QLIkOtKS4os&t=295s) together with the docs. Hope it helps!

**Comment by mkrech** [comment]
Thank you for your answer, I will hav a look into the class :)

kindly regards
michael
